### ISSUE TITLE
MozFest House wordmark/logo lockup

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/mozfest-design-2019#10]
### Description

Reuse from 2018, or tweak only slightly if needed.

### Reference from last year

**GitHub ticket:** https://github.com/MozillaFoundation/mozfest-design-2018/issues/32

**Comment by sabrinang** [comment]
This is exported here: https://drive.google.com/open?id=1bJMv_uTx_fXxTLTkxv-J8PhDLuMAs0Fh

This is also documented with our brand so it can be found: https://foundation.mozilla.org/en/docs/brand/design/logos/
