### ISSUE TITLE
Space icons

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/mozfest-design-2019#11]
### Description

Reuse the 6 space icons from last year and if we want, be prepared with an experience design (can reuse from last year). There may be new spaces/experiences that emerge after sessions are curated so we can design for them later.

### Reference from last year

**GitHub ticket(s):** 
- [Spaces](https://github.com/MozillaFoundation/mozfest-design-2018/issues/26)
- [Experiences](https://github.com/MozillaFoundation/mozfest-design-2018/issues/30)

**Comment by sabrinang** [comment]
Updated to include neurodiversity and queering icons in folder here: https://drive.google.com/open?id=11Su3bEhDScLpbxd1L6Y5UUuTqah1cgCe
