### ISSUE TITLE
Accessibility "understand me better" cards

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/mozfest-design-2019#13]
### Description

At the Youth, Press, and Accessibility table, there will be "Understand Me Better" cards the size of business cards for people to use to hand out when communication is difficult. Let's reuse them from last year.

### Reference from last year

**GitHub ticket:** https://github.com/MozillaFoundation/mozfest-design-2018/issues/45

**Comment by marcwalsh** [comment]
Here is the artwork template for these cards, it should be the same as last year however we're printing on a different type of (recycled) paper, so I'm not sure if bleeds etc have changed.

[Business Card - Artwork Files](https://github.com/MozillaFoundation/mozfest-design-2019/files/3551255/839_543_9000.zip)

**Comment by kristinashu** [comment]
I've copied the artwork over to the above template. For simplicity, I've also removed the black and yellow border from previous years artwork since they seem to have been cropped off anyways.

Files in drive folder https://drive.google.com/drive/folders/1n4tUSYEt4lQCWzZ_IhhpaSzQ3g90Yaoo?usp=sharing

[Mozilla-Festival-2019-Understand-Me-Better-Cards.pdf](https://github.com/MozillaFoundation/mozfest-design-2019/files/3592581/Mozilla-Festival-2019-Understand-Me-Better-Cards.pdf)

@sabrinang R+?

**Comment by sabrinang** [comment]
R+, Looks good @kristinashu 

Ready to Print @marcwalsh

**Comment by marcwalsh** [comment]
Hi @sabrinang and @kristinashu 

We had some feedback from the Neurodivsersity Team around what to include on the card to make them as useful as we can:

- Preferred name
- Any specialist interests
- Preferred communication/interaction or notice of session interaction: (I may interact, I would prefer not to interact, I’m happy to be asked to interact, I may choose to leave early)
- Please let me know if this session is interactive or requires interaction).
- The card could also include a ‘help me’ section which people could show to a wrangler for support  (eg: Can you help me find the quiet space, my session, toilets, food, drinks)

Let me know what you think is possible, we can make this A6 (105 × 148 mm) if necessary. I can get this printed pretty quickly, so next Wednesday / Thursday I would need the designs by.

Thanks!

**Comment by kristinashu** [comment]
Sure @marcwalsh, we'll get this updated and ready for print by Wed!

**Comment by kristinashu** [comment]
@marcwalsh yeah they'll have be on A6. Do you have the template for that?

Here's how the design is looking, @marcwalsh is the copy ok and @sabrinang is the design ok?

![Mozilla-Festival-2019-Understand-Me-Better-Cards-v2-03](https://user-images.githubusercontent.com/1068783/66863833-b8e1cb80-ef48-11e9-9f05-7ed3c752c979.jpg)

![Mozilla-Festival-2019-Understand-Me-Better-Cards-v2-04](https://user-images.githubusercontent.com/1068783/66863835-b8e1cb80-ef48-11e9-887e-8cbbb2fa39a3.jpg)

**Comment by sabrinang** [comment]
For the "Please let me know if this session is interactive or requires interaction" should this also be a checkbox instead of a heading? Unsure what is supposed to be filled after this or if it should be part of the previous section?

For the "help me" section, to have more room to write we could reduce number of examples?

@kristinashu Design is good and clear.

**Comment by kristinashu** [comment]
Made some copy and design updates:
![Mozilla-Festival-2019-Understand-Me-Better-Cards-v2-04](https://user-images.githubusercontent.com/1068783/66877703-61a12280-ef6b-11e9-955f-da08c36fd523.jpg)

**Comment by kristinashu** [comment]
I got the A6 template from the pixart site so @sabrinang if you could please give it one final review and then it should be ready for print!

[Mozilla-Festival-2019-Understand-Me-Better-Cards-A6.pdf](https://github.com/MozillaFoundation/mozfest-design-2019/files/3735381/Mozilla-Festival-2019-Understand-Me-Better-Cards-A6.pdf)

(PDF is also in drive [here](https://drive.google.com/file/d/11QFd7LiagkXzpGoEfgNsOhm_M-yQw5H6/view?usp=sharing))

**Comment by sabrinang** [comment]
@kristinashu Thanks for using the template, R+ on design file.

Not quite sure how the individual fills the "Is this session" section still (maybe framed with If) but will leave to Marc to review copy/content.

**Comment by marcwalsh** [comment]
Sent to print!
