### ISSUE TITLE
MozFest House window vinyl

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/mozfest-design-2019#14]
### Description

Branded window vinyls show up on a few windows at MozFest House. Let's just reuse them from last year.

### Reference from last year

**GitHub ticket:** https://github.com/MozillaFoundation/mozfest-design-2018/issues/70

**Comment by gideonthomas** [comment]
Update the pattern, dimensions and everything else is the same.

**Comment by marcwalsh** [comment]
Let me double check on this - it was done externally by the printer last year.

**Comment by gideonthomas** [comment]
@marcwalsh re-pinging about this ^

**Comment by sabrinang** [comment]
@marcwalsh are the printers we are going with this year blue ant (the ones we used in 2017) and can you confirm these are the dimensions?

<img width="861" alt="image" src="https://user-images.githubusercontent.com/2492510/64976995-6210a580-d867-11e9-8b3c-f7aeb188a52a.png">

**Comment by gideonthomas** [comment]
@marcwalsh checking in on this again

**Comment by sabrinang** [comment]
I've made a window design with large logo on redpen: https://redpen.io/p/ake2f9ef776b11677e

**Comment by marcwalsh** [comment]
@sabrinang - we talked about this in our production meeting today, we're happy to go with this. 

Would you be able to send a link to a PDF please and we'll send to the printers

**Comment by sabrinang** [comment]
The pdf is in gdrive here: https://drive.google.com/open?id=14aNAhUF0zh3O9q32H8VHKSe_3dXk943T&authuser=sabrina@mozillafoundation.org&usp=drive_fs

**Comment by LucieClick-MFHouse** [comment]
@sabrinang if you can also send to me at lclick@mozilla.com then I'll use this as a basis for the other house signage - any chance I could get this today so they can get started? Thanks!! Lucie

**Comment by sabrinang** [comment]
@LucieClick-MFHouse I sent it attached in the email as well as shared it via gdrive link too.

**Comment by sabrinang** [comment]
*Post-MozFest Documentation*
![10212019-mozfest-house-monday-social-9](https://user-images.githubusercontent.com/2492510/68495956-214d6100-0206-11ea-8651-587c07d63595.jpg)
