### ISSUE TITLE
MozFest House customizable signs

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/mozfest-design-2019#15]
### Description

A pattern/textured pattern in Google Slides that can be remixed to make letter size posters. This is a generic template to be remixed by Lucie and Marc and are used throughout the House venue for events and wayfinding. Let's just reuse them from last year.

### Reference from last year

**GitHub ticket:** https://github.com/MozillaFoundation/mozfest-design-2018/issues/65

**Comment by marcwalsh** [comment]
@gideonthomas @kristinashu - these could be pushed back further if required? They are printed on-site at MozFest House. So required before the 18th October.

**Comment by gideonthomas** [comment]
@marcwalsh we just want to get it off our docket so that we can work on other things.

**Comment by gideonthomas** [comment]
Reuse template, just update texture.

**Comment by kristinashu** [comment]
I've updated the background texture for the template https://docs.google.com/presentation/d/1Lo4hgdZFtvnu88vatXOYfFaOm6Iqoa_RU5qMLJye4Co/edit?usp=sharing

This is also in the main MozFest House folder https://drive.google.com/drive/folders/1Bpc25lZejSkFbCGK1Rv7-cd_KBDG1lx2?usp=sharing

@sabrinang R+?

**Comment by sabrinang** [comment]
@kristinashu Texture looks good! Can we include an option where the bottom border is a bit more narrow? These were used for some longer titles than expected and would be good to have some more white space above/below headings. Last year usage ref:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/2492510/64548349-4cd5cd00-d2e3-11e9-8273-a7d2e9c894d2.jpg">

**Comment by kristinashu** [comment]
Thanks Sabs! I've updated it so there is a larger white box https://drive.google.com/drive/folders/1Bpc25lZejSkFbCGK1Rv7-cd_KBDG1lx2?usp=sharing. For simplicity I think we should only have one version so I've just updated the one slide rather than adding a second one.

**Comment by sabrinang** [comment]
https://drive.google.com/open?id=1Lo4hgdZFtvnu88vatXOYfFaOm6Iqoa_RU5qMLJye4Co

R+ Nice margins and balance of space for text and one is great @kristinashu

Ready for print @marcwalsh

**Comment by sabrinang** [comment]
cc/ @LucieClick-MFHouse as you can use these as a basis for the other house signage too

**Comment by marcwalsh** [comment]
Thanks everyone, closing this as they're being used onsite at the moment
