### ISSUE TITLE
MozFest House folding screen

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/mozfest-design-2019#16]
### Description

Last year we had branded folding screens and totems. However, this year, we will only have the folding screens. Let's reuse these from last year.

### Reference from last year

**GitHub ticket:** https://github.com/MozillaFoundation/mozfest-design-2018/issues/66

**Comment by gideonthomas** [comment]
Reuse design (or use an existing texture from this year), fix logo as it wasn't printed properly last year.

**Comment by kristinashu** [comment]
According to last year https://github.com/MozillaFoundation/mozfest-design-2018/issues/66#issuecomment-439549193 the mozilla logo was printed without the white background and was printed at the fold. I did see a "missing asset" error when I open last year's file so I've replaced the logo for this year so hopefully that won't be an issue. But I'm not sure what to do about the folding. @marcwalsh can you please just confirm these dimensions? 

I've updated the background texture:

[Files in Drive folder.](https://drive.google.com/drive/folders/1lYNqaUAUpb5IFh164ufnbR2HbXdtzeLG?usp=sharing)

[Mozilla-Festival-House-2019_Folding-Screen.pdf](https://github.com/MozillaFoundation/mozfest-design-2019/files/3585826/Mozilla-Festival-House-2019_Folding-Screen.pdf)

@sabrinang R+?

**Comment by sabrinang** [comment]
@kristinashu Thanks for fixing the logo for this. For the right panel, add some pattern and/or orange? it's a bit of an even pink in comparison to the other two panels:
<img width="531" alt="image" src="https://user-images.githubusercontent.com/2492510/64739416-e39eb700-d4a6-11e9-8ac6-ffd2a9f14118.png">

@marcwalsh Will last years template print correctly with the folds in the right spot? Assuming we are going with this type again https://www.pixartprinting.co.uk/wide-format/printing-flat-bed-rigid-materials/folding-screen/

**Comment by kristinashu** [comment]
@sabrinang is this better? 

[Files in Drive folder.](https://drive.google.com/drive/folders/1lYNqaUAUpb5IFh164ufnbR2HbXdtzeLG?usp=sharing)

[Mozilla-Festival-House-2019_Folding-Screen.pdf](https://github.com/MozillaFoundation/mozfest-design-2019/files/3585826/Mozilla-Festival-House-2019_Folding-Screen.pdf)

_(screen cap)_
<img width="825" alt="image" src="https://user-images.githubusercontent.com/1068783/64884683-2c757d80-d617-11e9-9f8b-c1632aebb6ed.png">

**Comment by sabrinang** [comment]
@kristinashu Looking good, R+ on design.

Assigning @marcwalsh to confirm we have correct template and folds (https://www.pixartprinting.co.uk/wide-format/printing-flat-bed-rigid-materials/folding-screen/ ?) before it is ready for print.

**Comment by marcwalsh** [comment]
Thanks @kristinashu and @sabrinang  - I used the standard rigid media template and placed this design onto it (without fold marks) as we're just having one piece this year instead of folding it. 

Sent to print! 🎉
