### ISSUE TITLE
Icons for snippet and favicon

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/mozfest-design-2019#17]
### Description

The MozFest cog appears in the snippet and as a favicon on the website (potentially out of scope). Let's just use the black and white cog which is one of the designs from last year.

### Reference from last year

**GitHub ticket:** https://github.com/MozillaFoundation/mozfest-design-2018/issues/80

**Comment by sabrinang** [comment]
Icons and favicons can be found here: https://foundation.mozilla.org/en/docs/brand/design/logos/
