### ISSUE TITLE
Call for Proposal: Banner for Google Form

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2019#19]
**Description:**
Create a banner for the Mozilla Festival call for proposals google form. The template can be based on the updated form google form _([Google Forms](https://docs.google.com/forms) > Template Gallery > Mozilla > Mozilla Form Template - Logo Only)_

**Content:**
_TBD_

**Related Issues:**
CFP June Website issue: https://github.com/MozillaFoundation/mozfest-website-2019/issues/7#issuecomment-490218766

**Comment by sabrinang** [comment]
![Screen Shot 2019-05-15 at 4 24 40 PM](https://user-images.githubusercontent.com/2492510/57815858-07870180-772e-11e9-862a-59be1367b8f2.png)
![Screen Shot 2019-05-15 at 4 24 12 PM](https://user-images.githubusercontent.com/2492510/57815861-0950c500-772e-11e9-8f64-88a67370acbf.png)
![Screen Shot 2019-05-15 at 4 24 22 PM](https://user-images.githubusercontent.com/2492510/57815864-0a81f200-772e-11e9-9322-3f8c1d4f533b.png)

Banner images exported in gdrive here: https://drive.google.com/open?id=1sV7Y0BI9OzjkAuSNPCEY7bGNYwu-f3DN

These are also generic so you can use them for other mozilla festival 2019 forms

**Comment by gideonthomas** [comment]
@sabrinang any preference for Theme color and background color for the form?
