### ISSUE TITLE
Website look-and-feel

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/mozfest-design-2019#2]
### Description

Build on the [brand standardization work](https://github.com/MozillaFoundation/Design/issues?utf8=%E2%9C%93&q=is%3Aissue+sort%3Aupdated-desc+label%3A%22Brand+Standards%22) done for the foundation website to create a slightly more unique brand for MozFest 2019. This may be informed by the [style guide](1). 

Let the design process be informed by long-term goals of hosting MozFest on the foundation website so that only few design updates are needed every year. Let's try to focus on delivering something within two weeks and then iterating on it going forward.

#### Components

- [x] Final decision on platform (@gideonthomas)
- [ ] Template mockups
- [ ] IA

**Comment by gideonthomas** [comment]
confirmed that we will be using a Wagtail instance (not directly on foundation.mozilla.org, but should have the same capabilities) with the url mozillafestival.org.

**Comment by sabrinang** [comment]
Here are some docs for reference we can use in our kick off meeting:

Redpen on draft IA/April mockup: https://redpen.io/p/nzfb8f506e69e325bd

Website planning gdoc notes: https://docs.google.com/document/d/1hZ1lPsYNjuf6UJb-irwUbIQ22FHV-m1RM7ybG-wGs_c/edit#

@beccaklam @gideonthomas

**Comment by sabrinang** [comment]
I revised a single-page mockup after hearing feedback and ideas: https://redpen.io/npc9df3b0c504bc3b2

I am also testing/making it in wagtail here: https://foundation.mozilla.org/cms/pages/335/edit/preview/ - This is using a placeholder cta form, I will need to create a new sign-up form

**Comment by sabrinang** [comment]
Looking beyond April version of the website, there are a few pieces to be discussed for the June version and I filed them as issues here: https://github.com/MozillaFoundation/mozfest-website-2019/issues

All june wireframes can be found on redpen here: https://redpen.io/p/ds407a5700e4997ea2

**Comment by sabrinang** [comment]
Any further website planning we should probably do in the website repo instead (do we close this issue? @gideonthomas )

**Comment by gideonthomas** [comment]
We can if that's what you prefer or if you want to track design for the website here, we can do that too.

**Comment by gideonthomas** [comment]
@beccaklam do you want me to keep this ticket open? We're tracking website tickets (including design) in https://github.com/MozillaFoundation/mozfest-website-2019

**Comment by beccaklam** [comment]
Nope, I'll close it!
