### ISSUE TITLE
Photo/Video consent poster

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/mozfest-design-2019#21]
This poster appears in several spots on the ground floor of Ravensbourne and MozFest House. This will be branded for use in general Mozilla events and the language will be modified to not reference specific venue locations so that it can be reused across Mozilla events.

@gideonthomas to get content approved by Marc.

**Comment by sabrinang** [comment]
@siuhoylee Is currently iterating on these: https://redpen.io/p/wg544df015ceb9071a

**Comment by siuhoylee** [comment]
@sabrinang   I have done a version using Ninito Sans. I think I prefer this version. The main text is easier on the eye to read.  https://redpen.io/p/wg544df015ceb9071a

**Comment by siuhoylee** [comment]
Following on from my weekly catch-up call with Sabrina yesterday, the feedback was to use the same background/colour/texture as the Registration posters. We also discussed that the yellow and black lanyards will stay the same. We decided that the Namecard should be updated on the poster to reflect the new design and colours.

**Comment by siuhoylee** [comment]
@sabrina  @marc  In Red Pen there is what will be more or less the final Privacy Alert poster V4. The only thing that needs to be done is to update the Name Card design which appears on the poster. The Name Card design will be done in the 3rd of September according to Airtable production schedule.

**Comment by siuhoylee** [comment]
@marc @sabrina The updated Privacy Alert A3 Poster V5. Icons and Name Card have been updated. The text is the same as 2018. Here is the Red Pen link https://redpen.io/teb0d3c16ead084669    Here is the gdrive link https://drive.google.com/drive/folders/12rwXxksb82g3pwCnei005ghVgpWnanLR 
![Privacy-Alert_A3-Poster](https://user-images.githubusercontent.com/53485444/66662835-774bda80-ec41-11e9-95e3-8f7bf81db229.jpg)

**Comment by siuhoylee** [comment]
@marc  @sabrinang  I have updated the Privacy Alert A3 Poster. The text is the same as 2018. Here is the link on Red Pen https://redpen.io/pdbeb29eae55d9f71a  Here is the link to the artwork on gdrive https://drive.google.com/drive/folders/1hyGzos5hBtZSr301gnkPqPLDGSVw2dan
![MozHouse-Privacy-Alert_A3-Poster](https://user-images.githubusercontent.com/53485444/66668804-f7783d00-ec4d-11e9-8ca9-41d104f6f7ed.jpg)

**Comment by siuhoylee** [comment]
@marc @sabrinang  I have reverted to the 2018 background because the 2018 Participation Guidelines Poster has already printed. This will look consistent as they appear together. Here is the Red Pen link https://redpen.io/ts1298f0d083fb1d7e  The artwork on gdrive has been updated.
![V2 MozHouse-Privacy-Alert_A3-Poster](https://user-images.githubusercontent.com/53485444/66670516-e3ced580-ec51-11e9-9006-87c735e9d0b3.jpg)

**Comment by sabrinang** [comment]
@siuhoylee Texture and icon updates look good 👍  A3 pdfs are both good to go.

R+ Ready for Print.

**Comment by marcwalsh** [comment]
Sent to print!

**Comment by sabrinang** [comment]
**Post-MozFest Documentation**
Located by entrance area
![DSC04248](https://user-images.githubusercontent.com/2492510/68496171-90c35080-0206-11ea-9bf5-059e6a7e9019.jpg)
![IMG_20191026_131654](https://user-images.githubusercontent.com/2492510/68496100-6b364700-0206-11ea-995b-d6d0f4f7d538.jpg)
![DSC04024](https://user-images.githubusercontent.com/2492510/68496355-f6174180-0206-11ea-9aae-1dbe8cb50700.jpg)
