### ISSUE TITLE
Event participation guidelines poster

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/mozfest-design-2019#22]
This poster appears in several spots on the ground floor of Ravensbourne and MozFest House. This will be branded for use in general Mozilla events and the language will be modified to not reference any specific event for reusability as a template for Mozilla events. Contact information can be plugged into the template nearer the time. This will need to be localized.

@gideonthomas to get content approved by Marc.

**Comment by gideonthomas** [comment]
@marcwalsh is this copy fine for the poster?

---
### Participation Guidelines

This event has adopted the Mozilla Community Participation Guidelines and we require all those who participate to agree and adhere to them in order to help us create a safe and positive community experience for all.

#### How to treat each other:

- Be respectful and value each other’s ideas, styles and viewpoints.
- Be direct but professional; we cannot withhold hard truths.
- Be inclusive and help new perspectives be heard.
- Appreciate and accommodate our many cultural practices, attitudes and beliefs.
- Be open to learning from others.
- Lead by example and match your actions with your words.

#### The following will not be tolerated:

Violence and threats of violence; personal attacks; derogatory language; unwelcome sexual attention or physical contact; disruptive behaviour; influencing unacceptable behaviour.

---

This would be the template and the only change that should be done is to add contact information at the bottom of the copy for violations of the guidelines.

**Comment by sabrinang** [comment]
Poster designs for https://github.com/MozillaFoundation/mozfest-design-2019/issues/21 can align to inform this issue. Assigning to @siuhoylee since he's working the poster designs already.

**Comment by siuhoylee** [comment]
@sabrinang  Please see link: https://redpen.io/p/rvae25524bc27df936   This is the initial design. I think the red/blue colours draw attention which is I think important to the poster content. Please can I get some feedback on it. Thanks.

**Comment by siuhoylee** [comment]
@sabrinang   I have done a version with Nunito Sans font. I think it does look cleaner than Barlow and looks better.

**Comment by siuhoylee** [comment]
Following on from yesterday's weekly catchup with Sabrina, Siu will make cosmetic amends to the Participation Guidelines poster ie. use the same background/texture/colour as the Registration posters and I think it was agreed that we will stay with Zilla Slab and Barlow fonts.

**Comment by siuhoylee** [comment]
@sabrinang   @marcwalsh   In Red Pen there is the final version (V2) of the Participation Poster. This looks good to me. If there are any more amends for me to make or if approved just let me know. Thanks.

**Comment by siuhoylee** [comment]
@sabrinang  @marcwalsh  Here is the google drive link to the final artwork  https://drive.google.com/drive/folders/1YHmzz2QC1t9NogG6p8NP8AzzMjfb42up  
<img width="599" alt="MozFest-2019-Participation-Guidelines-EN-A3" src="https://user-images.githubusercontent.com/53485444/64777562-5a44be80-d552-11e9-8cb3-16de8dc92bb9.png">
![MozFest-2019-Participation-Guidelines-A3](https://user-images.githubusercontent.com/53485444/64777570-5e70dc00-d552-11e9-8328-b13de21c3af8.jpg)

**Comment by sabrinang** [comment]
@siuhoylee R- Design and template looks good but for the file consider outlining or embedding text for pdf exports, I'm getting missing fonts:
<img width="504" alt="image" src="https://user-images.githubusercontent.com/2492510/64820088-8cf7b280-d564-11e9-95b7-e6fb6899b920.png">

Also, for these files:
Mozilla-Festival-2019_Participation_Guidelines-ES-A3, 
 Mozilla-Festival-2019_Participation_Guidelines-FR-A3,  
Mozilla-Festival-2019_Participation_Guidelines-IT-A3,  
Mozilla-Festival-2019_Participation_Guidelines-PT-BR-A3 
they have “Mozill a” typo on the second line

Also, is MozFest House getting a participation guideline poster as well? I noticed it is missing from event participation guideline set or is that a separate issue?

**Comment by siuhoylee** [comment]
@sabrinang  I have amended all the text to outlined in all the pdfs. The typo correction has been made to ES, FR, IT, PT-BR. Thanks.

**Comment by sabrinang** [comment]
@siuhoylee R+ on type and typo fixes. 
https://drive.google.com/open?id=1YHmzz2QC1t9NogG6p8NP8AzzMjfb42up

@marcwalsh Checking with you if we need a MozFest House version or can use these MozFest ones for House? Note: we made specific ones last year but looking at photos it wasn't put up in the space (however it was used the year before though)

**Comment by marcwalsh** [comment]
@sabrinang - we will need MozFest House examples, but as Siu mentioned that we can reuse the designs from the weekend. 

It'll be a nice to have to ensure the House are fully updated with latest branding.

**Comment by siuhoylee** [comment]
@sabrinang  Sarah commented on possibly having the 10th anniversary on the top right. There a visual called V3 on https://redpen.io/p/rvae25524bc27df936

**Comment by siuhoylee** [comment]
@sabrinang  @marcwalsh   Note to Sabrina, the 10th anniversary motif appears on the poster. As discussed it is aligned and sized to match the Mozilla lock-up. Everything else including the text was left unchanged. The link to the artwork on Gdrive is https://drive.google.com/drive/folders/1YHmzz2QC1t9NogG6p8NP8AzzMjfb42up

<img width="1638" alt="Participation-Guidelines-Posters" src="https://user-images.githubusercontent.com/53485444/65950335-c0c44a80-e435-11e9-830d-9b8b366b1ad8.png">
<img width="633" alt="Participation-Guidelines-Poster" src="https://user-images.githubusercontent.com/53485444/65950340-c588fe80-e435-11e9-9c17-bb19bcb25601.png">

**Comment by sabrinang** [comment]
@siuhoylee R+ on design and all print ready PDFs look good on existing A3 pixart template.
https://drive.google.com/open?id=157A4KpMiN_WGUHfGjSLPT0ubOQWIA99i

@marcwalsh Ready for print

**Comment by marcwalsh** [comment]
Sent to print for large floor signs - I placed these on the template and will upload artwork later. 

MozFest House floor signs were reused from 2018 - these have been sent to print

Weekend A3 prints will be printed on site at Ravensbourne.

**Comment by sabrinang** [comment]
**Post-MozFest Documentation**
Placed by registration, outside D&D space and l10n versions along stairwell:
![IMG_20191026_131552](https://user-images.githubusercontent.com/2492510/68438556-624b6400-0179-11ea-8d24-0de2e6a88b5f.jpg)

![IMG_20191025_131357](https://user-images.githubusercontent.com/2492510/68438417-fb2daf80-0178-11ea-9d14-a3e41fe314bc.jpg)
![IMG_20191025_131321](https://user-images.githubusercontent.com/2492510/68438428-fe28a000-0178-11ea-9fa0-6bfab09fd945.jpg)

Some one made sharpie additions to this one, so I'm suspecting there may be typos here:
![DSC04246](https://user-images.githubusercontent.com/2492510/68438475-1f898c00-0179-11ea-97a4-d28307b99e65.jpg)
