### ISSUE TITLE
MozFest stage backdrops

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/mozfest-design-2019#23]
This is used for Dialogues and Debates as well as the opening ceremony. There is a dependency on stage measurements at Ravensbourne.

**Comment by gideonthomas** [comment]
Use textures from this year. @marcwalsh what are the dimensions for this?

**Comment by marcwalsh** [comment]
@gideonthomas Still TBC will know in the next couple of weeks.

**Comment by gideonthomas** [comment]
@marcwalsh any updates on this?

**Comment by marcwalsh** [comment]
Only a small update so far:
- Level 0 will be the same size stage as last year so the same dimms as 2018.
- Level 4 we're confiming if we can have an LED wall on the floor instead, so this can be a static or (ideally) a slightly animated backdrop. 

With the LED wall, we'll be looking to use a social media tool to display tweets etc, we're still confirming what software this is - but we're looking at curator.io

**Comment by sabrinang** [comment]
Based on last years dimensions, https://github.com/MozillaFoundation/mozfest-design-2018/issues/35#issuecomment-42599579:

Floor 0 - 500cm x 300cm (W x H)
Floor 4 - 400cm x 300cm (W x H) 

With an LED wall and potentially animated backdrop, should floor 4 stage be designed differently? 

@marcwalsh can you confirm any updates and that dimensions are correct?

**Comment by gideonthomas** [comment]
@marcwalsh would you be able to confirm ^

**Comment by marcwalsh** [comment]
@sabrinang @gideonthomas - sorry for the delay

Floor 0 is confirmed as the same size.

Floor 4 we're still awaiting costs for the shipping to make sure we can afford to bring over the LED. Ideally if using the screen we would have this as something that's animated. I'm hopefully confirming this week.

**Comment by sabrinang** [comment]
Iterating on Floor 0 stage design on redpen: https://redpen.io/p/ke337b2036f0cbadb9

**Comment by gideonthomas** [comment]
@marcwalsh re-pinging about this?

**Comment by marcwalsh** [comment]
Confirming that the stage backdrop for Level 4 will be 4x3m on a screen - I'm waiting on the resolution of the screen, will get that in the next day or two.

@sabrinang - you know know which design you want to go for the backdrop? Could I get an export in PDF of the chosen design please? (I really like the second with the cog!)

**Comment by sabrinang** [comment]
Revised design (included annual wordmark and simplified background) for Level 0: https://redpen.io/p/ke337b2036f0cbadb9

![Mozilla-Festival-2018_Stage-Level-0_500x300@0 25](https://user-images.githubusercontent.com/2492510/66878632-a4fd9000-ef6f-11e9-8b42-c6113f0061c7.png)

Print PDF 500x300: https://drive.google.com/open?id=1AhdLLClzlNseDLpHr2fvtIinumG634Xd&authuser=sabrina@mozillafoundation.org&usp=drive_fs

If you need it at 530x320 for bleeds .ai file is here: https://drive.google.com/open?id=1BY5qxzpFuLuuy6Lee7Grzth7lODcmLN3&authuser=sabrina@mozillafoundation.org&usp=drive_fs  (illustrator says dimensions are out-of-range to export as pdf)

**Comment by marcwalsh** [comment]
Thanks @sabrinang - sent to print!

I'll change this to a digital asset now for the Level 4 screen - the resolution is 1408 x 1056 px, it can be static or motion (ideally motion / something taken from the work being done in #55)

:)

**Comment by sabrinang** [comment]
Updated redpen with two static ideas for level 4 digital screen: https://redpen.io/p/ke337b2036f0cbadb9

PNGs on gdrive here: https://drive.google.com/open?id=1BbAg13B69ytkN37tdxzsdNA-NKHU2thW&authuser=sabrina@mozillafoundation.org&usp=drive_fs

If it's motion yeah it can depend on issue #55

**Comment by sabrinang** [comment]
**Post-MozFest Documentation**
D&D Stage
![48997114058_55c25b5409_k](https://user-images.githubusercontent.com/2492510/68499002-06cab600-020d-11ea-9d55-c76d120ff9a4.jpg)
![48998515722_5b52d8dc0b_k](https://user-images.githubusercontent.com/2492510/68499016-0f22f100-020d-11ea-8fe1-39942f9b3b99.jpg)
![48997763463_74394f6199_k](https://user-images.githubusercontent.com/2492510/68499005-07fbe300-020d-11ea-9624-03c908e562c7.jpg)
![48998540347_54d846c143_k](https://user-images.githubusercontent.com/2492510/68499010-0b8f6a00-020d-11ea-911a-d1d623cc7a1f.jpg)

Main stage or motion loop didn't get used, opening ceremony screen didn't get used but presentation slide is seen:
![48998290876_02c0d586d4_k](https://user-images.githubusercontent.com/2492510/68499029-15b16880-020d-11ea-8413-dfd15ee99ef8.jpg)

Main stage backdrop got remixed for closing party though!
![48998364061_b7e8a85e85_k](https://user-images.githubusercontent.com/2492510/68499042-1ba74980-020d-11ea-93ff-23d33a3ddce5.jpg)
