### ISSUE TITLE
Wall projection color scheme

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/mozfest-design-2019#24]
On the 4th floor, a floodlight covers the wall. The color of this is determined based on the style guide.

**Comment by kristinashu** [comment]
Here is the color palette 
<img width="951" alt="image" src="https://user-images.githubusercontent.com/1068783/64463920-aa3b0580-d0ba-11e9-8c50-598a8d732d1e.png">

but Sabrina usually does this on-site so I think we can close this ticket as there isn't really any prep to do.
