### ISSUE TITLE
Ti.To branding

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/mozfest-design-2019#25]
Branding the Ti.To ticket pages based on Mozilla Festival's brand.

@sabrinang can we try to reuse most of it from last year with minor tweaks? Any other info you need?

**Comment by gideonthomas** [comment]
@sabrinang would we be able to get this done soon? As ticket sales are opening soon.

**Comment by sabrinang** [comment]
Banner: https://drive.google.com/open?id=1P1Ye9P7hYSwZMfjNsmMibWrFKXEZ7109&authuser=sabrina@mozillafoundation.org&usp=drive_fs
![Mozilla-Festival-2019_Tito-Ticket-Banner@2x](https://user-images.githubusercontent.com/2492510/61574099-abfb2c00-aa6e-11e9-9f4e-f0882b6c8279.jpg)

If the page needs the annual lockup in the body it is here: https://drive.google.com/open?id=1_kbHpfkRmykxPQEmKfuMnSxH_SF8TcRW&authuser=sabrina@mozillafoundation.org&usp=drive_fs

**Comment by marcwalsh** [comment]
Hi @sabrinang - I'm not sure if Ti.To have changed their banner requirements but the dimensions need to be 1800×530px (2x), would you be able to resize this please? I've attached a screenshot so you can see the current crop as well.

![Screenshot_2019-07-22 Mozilla Festival 2019](https://user-images.githubusercontent.com/30226684/61635533-ad557000-ac8b-11e9-8b8a-c16fae385b0f.jpg)

**Comment by sabrinang** [comment]
@marcwalsh Thanks for giving the dimensions, I exported (retina 2x) it here: https://drive.google.com/open?id=1P4zBYP0OfAhlbbLE5wGk2b_mknTt6871&authuser=sabrina@mozillafoundation.org&usp=drive_fs
