### ISSUE TITLE
Volunteer ticketing banner

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/mozfest-design-2019#26]
To recruit volunteers, the ticketing page will feature a banner that will probably be reused from last year.

**Comment by marcwalsh** [comment]
@gideonthomas - Since this is on a Google Form I used the generic banner what was made for the Call for Proposals.

The form is available [here](https://forms.gle/TMc7cmLLPh7ndZw57).

I think we're okay with this if there's other pieces could be picked up instead.

**Comment by gideonthomas** [comment]
Oh ok, @beccaklam we can remove this off your plate then.
