### ISSUE TITLE
Social media display photo and profile banner

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/mozfest-design-2019#27]
We need a banner and profile photo for the mozfest twitter page. The profile pic will probably still be the cog. The banner should be more specific to MozFest 2019.

**Comment by gideonthomas** [comment]
To make evergreen without dates.

**Comment by beccaklam** [comment]
@gideonthomas do you happen to know the correct dimensions for the banner and profile photo? I did a quick search and got this:

Banner: 1500 pixels wide by 500 pixels tall
Profile photo: 400x400

**Comment by beccaklam** [comment]
@sabrinang would something like this work or do we want to use a photo for a banner again like last year?
![Artboard 1](https://user-images.githubusercontent.com/20977376/64566839-de196380-d324-11e9-86af-4d960bb64a75.png)

**Comment by sabrinang** [comment]
@beccaklam let's go with a photo that features people it can have colour treatment like the website or something but avoid anything choosing one with any year showing up (like current twitter banner photo) so it can be more everygreen.

I like the purple treatment on the display picture but i think the sphere competes with the logo on top I would keep it to subtle textre/patterns/gradient avoiding shapes beneath.

**Comment by beccaklam** [comment]
@sabrinang does this work?
![Artboard 1](https://user-images.githubusercontent.com/20977376/64798884-c8d54c80-d551-11e9-8411-032ce3e2dd83.png)

**Comment by sabrinang** [comment]
@beccaklam R+ Yup that photo and display photo works

**Comment by beccaklam** [comment]
Files are here: https://drive.google.com/drive/folders/1Nd1C6XgyJnvlaJx4yHtAoTR0yWzmTAX_?usp=sharing
CC: @gideonthomas

**Comment by gideonthomas** [comment]
Hi @KGorr, would you be able to update the MozFest twitter dp and banner please?

**Comment by KGorr** [comment]
Done!
