### ISSUE TITLE
On-site setup checklist and photography checklist

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/mozfest-design-2019#28]
A simple todo checklist with setup instructions closer to the festival.

**Comment by sabrinang** [comment]
@marcwalsh
I’m working on the on-site checklist (short supply list at end): https://docs.google.com/document/d/1j87rmfoi9M8qEuOamqO62K8Y4zuGR0hDyyRZDjg9z6k/edit?usp=sharing

I highlighted in red text of assets I’m not sure we have or unsure of how to install. This is mainly for sponsorship assets as I don’t know if they need design set-up or where they were planned to be. Another question is for floor stickers (or other assets) printed at Ravensbourne, will their techs cut them or will we have to?

Please review and add any additional information or changes to the doc as I’ll be sharing this with the design set-up volunteers for them to reference for setting up.

_____________

I believe @zee-moz is updating the photography checklist here: https://docs.google.com/document/d/15K1a-60fRxAI1aYQpweGv2ExbmVtx4mLKUbYGVVG9z8/edit?ts=5bd04630

**Comment by sabrinang** [comment]
I confirmed with the design team that they will be onboard for onsite set-up:
- Kristina/Natalie will be ready to help from Wednesday onwards; 
- Tais/Becca will be ready to help from Thursday onwards;
- Mavis will be ready to help from Thursday onwards;

I think Anil will also be around to help (I have not confirmed with him yet)

cc/ @Saallen you can direct any additional volunteer names for me here and confirm which level/room we will be based at for prep work

**Comment by Saallen** [comment]
Hey other sign-ups were Abdoul and Youri
Set up on Wed will be the TV studio on the ground floor to connect with Marc

**Comment by zee-moz** [comment]
FYI here's this year's shot list, in progress.
https://docs.google.com/document/d/19EnDsplkfcDg9PJ9RxGFZ6ip4vW43LKZl5ThwlbkIVg/edit
