### ISSUE TITLE
Social graphics for ticket sales

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/mozfest-design-2019#29]
Have social graphics similar to last year: https://github.com/MozillaFoundation/mozfest-design-2018/issues/10

Let's use the same copy with this year's dates for house and the weekend.

Since we're using the same copy and the dates weren't localized last year, let's use the same localized ones as well.

**Due Date**: By June 21st or latest by October 1st

**Comment by sabrinang** [comment]
@beccaklam fyi there's a few unused ticket ideas (from tito banner draft file) that you may re purpose or find helpful for this issue: https://drive.google.com/open?id=1LlVpu-Ub7w1B2S9wur6F0lBrEz77WDeZ&authuser=sabrina@mozillafoundation.org&usp=drive_fs

**Comment by beccaklam** [comment]
@gideonthomas Do you know how many graphics we're thinking?

**Comment by beccaklam** [comment]
@sabrinang should I do squares for everything? 1080x1080?

**Comment by sabrinang** [comment]
@beccaklam You can use the social media template (twitter): https://drive.google.com/open?id=1RuvhwwnrpvC7GD4WG_qVuDsAaZQpLpVZ

**Comment by gideonthomas** [comment]
@beccaklam sorry, if we can just recreate stuff from here: https://drive.google.com/drive/folders/1YBdmf0wKYs3bvRoyN-IDyLsYs_N_-R83 with updated dates and branding, that should be good enough. Ideally they are localized as well and you can use the same copy from last year (ticket is linked in the original comment)

**Comment by beccaklam** [comment]
@gideonthomas @sabrinang do we need 4 versions of 3 graphics? Sabs made 12 graphics per language last year. Just making sure before I start?

**Comment by beccaklam** [comment]
@sabrinang Can I get some feedback please? https://redpen.io/p/hn8e17b3686e11dbc6

**Comment by beccaklam** [comment]
Graphics and working file here: https://drive.google.com/drive/folders/1ZQNssNsLljIh2BCgLvw5VcLac6R4FqUG?usp=sharing @gideonthomas who should i show to get signoff before closing this ticket?

**Comment by gideonthomas** [comment]
Awesome, thanks @beccaklam! We don't have a signoff process, I can close the ticket once we confirm that the dimensions are good. 

@KGorr we have ticket sales graphics for social 🎉. Can you verify if the dimensions are fine for twitter.

**Comment by KGorr** [comment]
Woohoo! This is what is most current:

For tweeted images:

Image width/height: Minimum 600 X 335 pixels, although larger images (for example 1200 X 675) will be better optimized for when users click to expand images.

Aspect ratio: 16:9.

Image file size: Max 15mb on twitter.com and 3mb on ads.twitter.com.

File types: PNG, JPEG, or GIF are recommended. Twitter does not accept BMP or TIFF files.

**Comment by gideonthomas** [comment]
@beccaklam does that work ^

**Comment by beccaklam** [comment]
@gideonthomas @KGorr I've updated the graphics to the above dimensions and changed the text to white on black. Everything is here: https://drive.google.com/drive/folders/1ZQNssNsLljIh2BCgLvw5VcLac6R4FqUG?usp=sharing

**Comment by marcwalsh** [comment]
@zee-moz - here's the artwork
