### ISSUE TITLE
Presentation slide template

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/mozfest-design-2019#3]
### Description

Create a Google slides template that can be used for a variety of presentational purposes. Let's use (or create) something more Mozilla-specific so that it can be used for other purposes as well. With the Mozilla-specific template, let's just tweak it to add the MozFest wordmark and if you want, a very minor design tweak to add the MozFest flair. Keep it simple.

### Reference from last year

**GitHub ticket:** https://github.com/MozillaFoundation/mozfest-design-2018/issues/101

**Comment by beccaklam** [comment]
Started this work here: https://docs.google.com/presentation/d/1e02Sv7lRw1YTBQ2Ie7UC-0Q4WEg1Z2i0Ln4ViJfrW6Y/edit?usp=sharing

design review: @sabrinang 
@gideonthomas who besides Sabrina needs to see this in order to close this ticket?

**Comment by gideonthomas** [comment]
No one, @sabrinang's approval closes this ticket once it's documented wherever it needs to be documented (style guide? fo'mo/docs/brand?). Once this closes, I can let the MozFest folks know that it's ready.

P.S. Love all of those designs.

**Comment by sabrinang** [comment]
@beccaklam These look great and good variety! I left some comments on the doc and can summarize:

Only design changes are swapping out some lockups and I think label for usage would simplify the options:
- the red/cyan + blue/purple for main templates (Mozilla Zone + MozFest Weekend use)
- the orange/red for MozFest House templates
- the multi-green for science fair template

**Comment by beccaklam** [comment]
Hey @sabrinang is this what you mean by labelling?
![image](https://user-images.githubusercontent.com/20977376/63521994-86c26900-c4c5-11e9-8683-925c29f413d7.png)

**Comment by beccaklam** [comment]
This is done!

**Comment by sabrinang** [comment]
**Post-MozFest Documentation**
![DSC04235](https://user-images.githubusercontent.com/2492510/68499526-38904c80-020e-11ea-9464-8549456dcb79.jpg)
![IMG_20191026_091831](https://user-images.githubusercontent.com/2492510/68499560-4e9e0d00-020e-11ea-9e4d-2442c7036714.jpg)
