### ISSUE TITLE
Onboarding Graphic Design Contractor

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2019#34]
Thursday meeting to onboard contractor with Marc and Gideon.

**Comment by sabrinang** [comment]
We did some planning today and onboarding meeting will be on Monday.

**Comment by sabrinang** [comment]
I met with the contractor this morning and I helped onboard by screensharing/walkingthrough:

- [Github Repo MozFest-Design-2019](https://github.com/MozillaFoundation/mozfest-design-2019)
          -  @gideonthomas Can you add Siu as collaborator/write access to the repo or make me admin so I can do so?
          - @gideonthomas @marcwalsh Who will be writing github issues for Siu? I didn't know how to answer this Q but I also don't know 

- [Redpen](https://redpen.io/projects) and I added Siu's LDAP to team account
- [Google Drive folders](https://drive.google.com/drive/folders/0B4Q8pzCpDS_eeXZyWkdQa2hNOXc?usp=sharing) and shared/added Siu's LDAP
         - folder structure, desktop syncing, naming convention, drafts organization etc.
- [Style Guide documentation deck](https://docs.google.com/presentation/d/1TUAe-GJ2ICSRV4VeC_Zur0Fmc3oXY5GJm1U6RV7NIa0/edit?usp=sharing)

- Illustrator files
          - workflow, libraries and using assets/effects

We covered a lot and they're still setting up accounts so I mentioned I'll be available on slack for further questions and assistance.

**Comment by gideonthomas** [comment]
> Can you add Siu as collaborator/write access to the repo or make me admin so I can do so?

What is Siu's Github handle?

> Who will be writing github issues for Siu? I didn't know how to answer this Q but I also don't know?

@marcwalsh or Siu can do this on their own. The Airtable view of tasks is https://airtable.com/shrC4AqMVWbIzFUdw and can also be found in the description of this repo. Marc can decide whether he or Siu will file the tickets. One suggestion is for Siu to file tickets as they start working on them.

**Comment by marcwalsh** [comment]
@gideonthomas - Siu's handle is @siuhoylee

@sabrinang - Siu and I will work through making them when we start on each piece of work or further in advance if we have time.
