### ISSUE TITLE
#MozHelp Signage

### ISSUE THREAD

**Issue by marcwalsh** [MozillaFoundation/mozfest-design-2019#36]
**Description**
Appears at the #MozHelp desk. This will remain the same as last year with a brand update and font change for reuse at other Mozilla events.

**Format**
- [ ] Metal Bus Stop Sign
- [ ] Floor Sign
- [ ] Table Front sign
- [ ] Plastic Mini Stand Sign

**Printer and Delivery Specs**
TBC

**Reference from Last Year**
[GitHub Issue](https://github.com/MozillaFoundation/mozfest-design-2018/issues/47)

**Comment by siuhoylee** [comment]
@sabrinang   Hi Sabrina, please can you look at some initial designs for the MozHelp floor sticker and let me know your thoughts. Here is the link: https://redpen.io/p/zp36ffdce9f9093666

**Comment by siuhoylee** [comment]
@sabrinang  When you have time this week please have a look and feedback on the #MozHelp Floor Sign.  Thanks. The redpen link is  https://redpen.io/p/kq827af7b59a4bcfc7

**Comment by siuhoylee** [comment]
@sabrinang  Also please see the #MozHelp Large Booth Sign.

**Comment by siuhoylee** [comment]
Received Sabrina's feedback from V1 design on Red Pen. I will make the necessary minor amends for next week's call with Sabrina. The amends on the floor sign is to make the 3d arrow smaller and on the large booth sign to consider using a mesh gradient instead of linear so that it matches the gradients in the posters and add the 3d arrow.

**Comment by siuhoylee** [comment]
@sabrinang  @marcwalsh  Following on from your comments on V1 Sabrina, there is V2 in Red Pen. Please add any comments. Thanks.

**Comment by siuhoylee** [comment]
@sabrinang  @marcwalsh  Note to Sabrina: Please see V3 in Red Pen of the amended #MozHelp Floor Sign and Table Front Sign. Please add any comments. Thanks.

**Comment by siuhoylee** [comment]
@sabrinang The Table Front Sign has been amended for review on Red Pen  https://redpen.io/p/kq827af7b59a4bcfc7. Thanks.

**Comment by sabrinang** [comment]
@siuhoylee nice, I have no more feedback to add to redpen, please export files for on github for design review

**Comment by siuhoylee** [comment]
@sabrina @marcwalsh  Here is the link to the final artwork on gdrive for design review
![#MozHelp-Table-Front-Sign](https://user-images.githubusercontent.com/53485444/65029945-8be4cd80-d936-11e9-9a5f-cb3f4ad648e3.jpg)
![#MozHelp-Floor-Sign](https://user-images.githubusercontent.com/53485444/65029951-8edfbe00-d936-11e9-9c09-788171c77419.jpg)

  https://drive.google.com/drive/folders/1yqrfFsbS5tw2B2NWrUfJb5ZX9jTA5Cjk

**Comment by sabrinang** [comment]
@siuhoylee Looks good matching the stroke widths, type outlined and exporting with bleeds. The floor sign left/right space looks a bit narrow after bleed crop compared to the top/bottom of it, you can match it similarly to the top/bottom spacing and it's good to go

**Comment by siuhoylee** [comment]
I have amended the artwork, the margins are uniform. I have saved over the previous artwork in google drive folder. 
![#MozHelp Floor Sign amended](https://user-images.githubusercontent.com/53485444/65134377-1ba07f80-d9fc-11e9-8931-a8fd6fed7f8a.jpg)

**Comment by sabrinang** [comment]
@siuhoylee R+ Thanks Siu, bleeds/margins balanced and looks good.

Ready for Print.

**Comment by sabrinang** [comment]
**Post-MozFest Documentation**


![DSC04206](https://user-images.githubusercontent.com/2492510/68437551-2fec3780-0176-11ea-8ecc-fbd78aadc6ec.jpg)
![DSC04205](https://user-images.githubusercontent.com/2492510/68437555-31b5fb00-0176-11ea-9a69-f02fabdd4f1d.jpg)
