### ISSUE TITLE
Registration posters

### ISSUE THREAD

**Issue by siuhoylee** [MozillaFoundation/mozfest-design-2019#37]
**Description:**
These large posters appear around the registration area and include posters for Registration, Name card customization, Swag, and Youth Press Accessibility. This might include logos of the Presenting, Champion, and Partner sponsors. Once the posters have been rebranded and the font updated to use Zilla, sponsors can be added to the template.

**Format:**
710mm width x 1010mm height

**Printer and Delivery Spec:**

**References from last year:** 
https://github.com/MozillaFoundation/mozfest-design-2018/issues/44

**Comment by siuhoylee** [comment]
@sabrinang   Here is the link to a initial design for the Registration Posters. I have tried it with the Zilla and Nunito Sans fonts but in my opinion Barlow Condensed looks the best. Let me know what you think.

**Comment by siuhoylee** [comment]
@sabrinang   Sorry the link is https://drive.google.com/open?id=1mht_JHWRihRUFUX_HyMFyT9VvXskGGzV

**Comment by siuhoylee** [comment]
@sabrinang   Please see the RedPen link. We can discuss on Thursday.  https://redpen.io/p/ya9d1ef13436687080

**Comment by siuhoylee** [comment]
@marcwalsh  Following on from my weekly catchup call with Sabrina, she said the Registration posters look fine. The only thing she did comment on was that the colours and textures should also appear the same on the Disclaimer posters. At the moment they do not look at the same.

**Comment by siuhoylee** [comment]
@marc  @sabrinang   I have revisited the Registration Floor Displays and in Red Pen there is a V2. I think this works much better than previous design. Sometimes its good to come back to things with a fresh eye.

**Comment by siuhoylee** [comment]
Here is the link to the final pdf artwork (4 Registration posters)  https://drive.google.com/drive/folders/1G2HIGYvldg9Ge3SF7ouIdE6_BKi-8cyw
![Registration_poster](https://user-images.githubusercontent.com/53485444/64694779-6d905500-d492-11e9-9baf-1a400e4654d8.jpg)

**Comment by sabrinang** [comment]
R+ on designs - Ready for print 👍

**Comment by marcwalsh** [comment]
We updated the Number 3 as we are not giving Swag out, so instead it's 'How To MozFest' for where people are collecting their book. 

Sent to print!!

**Comment by sabrinang** [comment]
**Post-MozFest Documentation**
Registration signage by entrance area
![IMG_20191026_131654](https://user-images.githubusercontent.com/2492510/68496506-5f975000-0207-11ea-8cfa-4602d95ebac6.jpg)
![IMG_20191026_131712](https://user-images.githubusercontent.com/2492510/68496510-632ad700-0207-11ea-90c3-7b5ce57dbae0.jpg)
![IMG_20191026_131552](https://user-images.githubusercontent.com/2492510/68496525-66be5e00-0207-11ea-981c-b7494692b2ec.jpg)
![DSC04254](https://user-images.githubusercontent.com/2492510/68496544-750c7a00-0207-11ea-8a26-3e2112e970ac.jpg)
