### ISSUE TITLE
Name Card Stickers: (language / pronoun / icebreaker)

### ISSUE THREAD

**Issue by siuhoylee** [MozillaFoundation/mozfest-design-2019#38]
**Description**
Create a sticker system that we can use to customize attendee name tags based on lanyard design. These stickers are used on name cards to indicate languages spoken by and personal pronouns of an attendee. 

These stickers include:

**Language Stickers**
This year, only a single language sticker with the words (possibly an icon) "I speak" will be designed with space to write down languages themselves. 

**Pronoun Stickers**
To remain the same as 2018 with minor design updates.

**Icebreaker Stickers**
To remain the same as 2018.

**Specifications**
Matte (non-glossy) finish so pen/markers can write on them easily and these can be printed on sheets. 

**Label Dimensions**
Custom size: 60mm x 30mm
9 designs for language stickers

Custom size: 30mm x 30mm
5 designs for pronoun stickers
1 design for icebreaker sticker

**Reference from last year**
https://github.com/MozillaFoundation/mozfest-design-2018/issues/58

**Comment by siuhoylee** [comment]
@sabrinang  Hi Sabrina, I've done some initial designs for the Language Stickers and are on Red Pen: https://redpen.io/p/jpdf4a28cae371919d   This is a generic design, possibly printed on different colours and will be printed Matte so people can write down their language/s.

**Comment by siuhoylee** [comment]
@sabrinang   In Red Pen there is a visual for the Name Card Prounoun Stickers, same link as above. I added more colour from the 2019 guidelines. If you have any comments, just add them to Red Pen. Thanks.

**Comment by siuhoylee** [comment]
Following from yesterday's catch-up call with Sabrina, the feedback for the language stickers was to amend the speech bubble so that it is not too close to the trim edge. Also use the speech bubble icon from Mozilla iconography set because it is a square design with rounded corners which will make use of the space on the sticker.
A question for @marcwalsh Sabrina suggested using one colour stickers instead of multi-coloured stickers because this could get confused with the coloured Spaces.
The only comment from Sabrina for the Pronouns sticker was to revert the font Nunito Sans back to Barlow.
A good point from Sabrina was to consider how it will look overall on the Name Card. Currently the Name Card hasn't been designed yet. So something to consider and we should review these stickers with the Name Card together.

**Comment by marcwalsh** [comment]
Hey @siuhoylee - one colour make sense for sure - that's totally fine by me.

**Comment by siuhoylee** [comment]
@sabrinang  @marcwalsh   Hi, I have revisited the Language sticker and have done a V2 in Red Pen as one single colour (green in this case - I have used a slightly darker tint to last year's green). Apparently green signifies 'peace, stillness, nature', so should appeal to all.

**Comment by marcwalsh** [comment]
We reused the 2018 sticker designs.

This year we've ordered:

- 1500x blank language stickers
- 750x blank pronouns
- 500x he/him
- 500x she/her
- 300x ask me
- 300x they/them

**Comment by sabrinang** [comment]
**Post-MozFest Documentation**
At customise your name tag station
![IMG_20191026_131712](https://user-images.githubusercontent.com/2492510/68496717-d2a0c680-0207-11ea-8c35-88188cd035fb.jpg)
![48997631171_4908347753_k](https://user-images.githubusercontent.com/2492510/68498074-dda92600-020a-11ea-9120-518a3d46725b.jpg)

**Comment by sabrinang** [comment]
![DSC04215](https://user-images.githubusercontent.com/2492510/68498464-bbfc6e80-020b-11ea-8493-5f356429f66e.jpg)
