### ISSUE TITLE
Map Legend Stickers

### ISSUE THREAD

**Issue by siuhoylee** [MozillaFoundation/mozfest-design-2019#39]
**Description**
Small stickers - Stickers representing the washroom, lunch, coffee, water, stairs and info booth will be printed for use on the map layout. Additionally, numbers and letters will be printed.

Large stickers - Stickers representing each space/experience, washroom, lunch, coffee, water will be printed for use on the "On this floor" poster.

**Specification**
TBC

**Comment by siuhoylee** [comment]
@sabrinang  Here is a Red Pen link to initial designs for the Map Legend Stickers. The small sticker dimensions are 30mm x 30mm.

**Comment by siuhoylee** [comment]
@sabrinang  https://redpen.io/p/sed20ce0cb544c955c

**Comment by siuhoylee** [comment]
Following from my weekly catch-up with Sabrina yesterday. The feedback was to consider using existing icons from https://foundation.mozilla.org/en/docs/brand/design/iconography/    I could add new ones to the set that match. For example the icon I designed for washroom currently doesn't look consistent because it is an an angle but there is already an icon in the Mozilla iconography set.

**Comment by marcwalsh** [comment]
These stickers will now be inclued on the Google Slide deck template (#41) for wranglers as the map will be on screens and not printed.

**Comment by marcwalsh** [comment]
Closing as they're being used in #41
