### ISSUE TITLE
Sponsor invitation email graphic

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/mozfest-design-2019#4]
### Description

We send email invitations to sponsors to attend MozFest using our ticketing platform. These invitations need to be more presentable than just regular text. Let's go with what we have last year and update to 2019 and change the background.

### Reference from last year

**GitHub ticket:** https://github.com/MozillaFoundation/mozfest-design-2018/issues/79

**Comment by beccaklam** [comment]
@sabrinang Can I get some feedback? https://redpen.io/p/ok5c7ee1f82bdb9b47 Also, do I need to make any other graphics for this ticket?

**Comment by beccaklam** [comment]
Graphic here and working file here: https://drive.google.com/drive/folders/12GXZa6PdGyhlOrtc2vx-FlI_LVejqriE?usp=sharing

@gideonthomas Not sure who needs to look over this before I can close the ticket?

**Comment by gideonthomas** [comment]
I'll pass it over to Juan to review (don't anticipate any changes). Thanks @beccaklam!

**Comment by gideonthomas** [comment]
They like it
