### ISSUE TITLE
10th Anniversary Design motif/graphic

### ISSUE THREAD

**Issue by siuhoylee** [MozillaFoundation/mozfest-design-2019#40]
Design a 10th anniversary motif / graphic for use across various assets

**Comment by siuhoylee** [comment]
@sabrina. @marc  Here is the Red Pen link to some initial ideas/designs  https://redpen.io/p/hu0fba0f97360e0320.  Let me know what you think, likes and dislikes. Thanks.

**Comment by siuhoylee** [comment]
@sabrinang   @marcwalsh   There is a V2 of the further developed cube 10th Anniversary graphic. I tried it with the cog but in my opinion it doesn't work because it looks too busy and also when placed alongside the MozFest logo it seems to clash. I wanted to keep it as simple as possible so that the 10th Anniversary is clearly visible, so I think just the cube on its own does that. I have placed it onto a mock up of the Festival Guide just to see how it could look like.
Here is the Red Pen link and feel free to comment. https://redpen.io/p/hu0fba0f97360e0320

**Comment by sabrinang** [comment]
Nice iterations so far @siuhoylee I left some comments on refining the dimension, margin and shading for the graphic.

**Comment by siuhoylee** [comment]
@sabrina  @marcwalsh   Hi Sabrina, in RedPen there is a V3 of the 10th Anniversary graphic. Let know what you think.

**Comment by siuhoylee** [comment]
@sabrinang  @marc  There is a new design, V4 in RedPen. I think this works well because it is consistent in design to the AI theme graphic: https://www.mozillapulse.org/entry/1266 Though I haven't yet tried it the words years or anniversary.

**Comment by siuhoylee** [comment]
@marcwalsh  @sabrinang  I think the 10th Anniversary motif/graphic and the 10th Anniversary background pattern are done to the point that we can now apply them to different assets such as the Festival Guide, Coffee Cups, T-shirts, Name Card, Entrance Floor Signage, Swag Sticker, etc.

**Comment by siuhoylee** [comment]
@sabrina  @marc  Note to Sabrina: I have increased the margin space around the word Years. This should make it more balanced.

**Comment by siuhoylee** [comment]
@marc  @sabrinang  Here is the link to the 10th Anniversary motif and pattern artwork  https://drive.google.com/drive/folders/17xPO7SE4kMGrJmdNOliJcruzptp-YCbQ
![10th Anniversary motif](https://user-images.githubusercontent.com/53485444/64701142-1b563080-d4a0-11e9-89f4-02fb92ccd607.jpg)
<img width="746" alt="10th Anniversary pattern" src="https://user-images.githubusercontent.com/53485444/64701152-227d3e80-d4a0-11e9-9f35-3f85f5b0fbce.png">

**Comment by sabrinang** [comment]
R+ Nice work @siuhoylee thanks for including the typeface with the vectors in the folder as well. Closing issue - as this motif itself is complete and will be applied in other assets.

**Comment by sabrinang** [comment]
![DSC04032](https://user-images.githubusercontent.com/2492510/68496849-1abfe900-0208-11ea-880a-f7be5a7ea4b8.jpg)
![DSC04182](https://user-images.githubusercontent.com/2492510/68496875-26131480-0208-11ea-9ec7-4eca39f91919.jpg)
![DSC04183](https://user-images.githubusercontent.com/2492510/68496876-26131480-0208-11ea-92cb-396796e5a3da.jpg)
