### ISSUE TITLE
Digital Displays for Maps and Schedule

### ISSUE THREAD

**Issue by marcwalsh** [MozillaFoundation/mozfest-design-2019#41]
### Description
This year we're looking to have monitors instead of the totems at the entrance to each space. 
Displaying on the monitors will be a Google Slide deck, containing the map of the level and the current session in each space (pulled from Google Calendar schedule).

Wranglers will have access to the slide deck for their space to be able add their own room numbers and icons as necessary.

### WIP Doc
Currently working on the script to get the session info from Google Calendar which can be found here: https://docs.google.com/presentation/d/1-gcWiOF4XZAqTzjSMBeqYLm7t4tYGmjCH0_f9cWRXZ8

**Comment by siuhoylee** [comment]
@sabrinang  @marcwalsh  Map icons and map designs are on Red Pen https://redpen.io/nr367e08525b970ae4

**Comment by sabrinang** [comment]
@siuhoylee left some design feedback on the redpen

Check the link Marc linked to in the issue comment above. I'm not too sure what the google calendar schedule would need and if that display need to be designed? The screens according to the deck look vertical too so your map mockups can fit that format but that link looks WIP so you'll need to confirm

**Comment by siuhoylee** [comment]
@sabrinang  @marcwalsh  @Saallen  V2 of the maps is in Red Pen for feedback.

**Comment by marcwalsh** [comment]
Thanks @siuhoylee  - I left feedback on the floor with updated locations etc.

**Comment by siuhoylee** [comment]
@marcwalsh  @sabrinang  V3 of maps are done and are on Red Pen  https://redpen.io/sfcca81f4e3e51f8fb

**Comment by sabrinang** [comment]
@siuhoylee left some design feedback for maps on redpen

**Comment by siuhoylee** [comment]
@sabrinang @marc  Thanks Sabrina. V4 is up on Red Pen.

**Comment by sabrinang** [comment]
**Post-MozFest Documentation**

Schedule with a filtered view may have been used instead:
![DSC04069](https://user-images.githubusercontent.com/2492510/68439481-970cea80-017c-11ea-9752-019fa4148d86.jpg)
