### ISSUE TITLE
Coffee Cups for MozFest House

### ISSUE THREAD

**Issue by marcwalsh** [MozillaFoundation/mozfest-design-2019#42]
## Description
Biodegradable coffee cups for MozFest House. The entire cup is branded. We're looking to use a similar design to last year but possibly including the newer textures (eg. static).

**Coffee Cups from 2018:**
![image](https://user-images.githubusercontent.com/30226684/63865467-8c2e2080-c9a9-11e9-9c0a-a20680377d12.png)

## Supplier / Template

Supplier: [Scyphus Paper Cups](https://www.scyphuspapercups.co.uk/products/takeaway-coffee-cups-double-wall-cups) - Biodegradable 8oz Double Wall Cups
Template: [8OZ-DW-SCY300X300-DOUBLE WALL CUP-TEMPLATE.ai](https://github.com/MozillaFoundation/mozfest-design-2019/files/3551507/8OZ-DW-SCY300X300-DOUBLE.WALL.CUP-TEMPLATE.ai.zip)

## References from 2018
2018 Ticket: https://github.com/MozillaFoundation/mozfest-design-2018/issues/69
2018 Asset Files: https://drive.google.com/drive/folders/1rgzuO7ljsuHYgymZ7cXVRLbqJZWcl7-q

**Comment by siuhoylee** [comment]
@sabrinang  @marcwalsh  In Red Pen there is a visual of the MozFest Coffee Cup design. https://redpen.io/p/je2691718bdbf7bd36  The coffee cups are the same size as 2018. Sabrina, please add any comments.

**Comment by siuhoylee** [comment]
@sabrina  @marc  I have made the amends to the MozFest House Coffee Cups following Sabrina's feedback. V3 is on Red Pen awaiting feedback.

**Comment by siuhoylee** [comment]
@sabrinang  @marcwalsh   In Red Pen there is a V4 Final artwork of the MozFest House coffee cup design. I have checked and aligned the black border, square pattern, Mozilla Festival House text aligns with the ruler guide.
![MozFest House 2019 Coffee Cup](https://user-images.githubusercontent.com/53485444/64687532-96a8e980-d482-11e9-8688-8e26ae900769.jpg)

**Comment by siuhoylee** [comment]
Final artwork can be found here  https://drive.google.com/file/d/1Ptj8zLTvu1s6lUStWoinTfKSSk_zB8Pr/view?usp=sharing

**Comment by LucieClick-MFHouse** [comment]
Looking good!

**Comment by sabrinang** [comment]
R+ Design and alignment on curve looks great @siuhoylee 

Can you also check final file for print is sorted in the google drive folder? (your link is diff from a V2 pdf I see in the coffee cups folder and you can file old versions in a zArchive folder if needed)

Ready for Print 👍

**Comment by siuhoylee** [comment]
V1 of the artwork had some text which was not outlined, hence there is a V2. I have also added V2 eps file too. Final print ready pdf link is https://drive.google.com/drive/folders/1i5avCLUnxEMVy-EgCwRnThVKch66-jK_

**Comment by sabrinang** [comment]
Great thanks for clarifying :+1: https://drive.google.com/drive/folders/1i5avCLUnxEMVy-EgCwRnThVKch66-jK_?usp=sharing

**Comment by marcwalsh** [comment]
Sent to print! ☕️

**Comment by sabrinang** [comment]
**Post-MozFest Documentation**
![10222019-mozfest-house-tuesday-14](https://user-images.githubusercontent.com/2492510/68496937-4642d380-0208-11ea-858c-14992d09dfab.jpg)
![10222019-mozfest-house-tuesday-10](https://user-images.githubusercontent.com/2492510/68496939-46db6a00-0208-11ea-942a-0afe933111c4.jpg)
