### ISSUE TITLE
Coffee Cup Swag

### ISSUE THREAD

**Issue by siuhoylee** [MozillaFoundation/mozfest-design-2019#43]
Part of the swag package provided to attendees. A stronger material water bottle would ideally be used. Previously this only had the MozFest icon on it. This year, if a sponsor purchases the water bottle swag add-on, we would need to add their logo as well.

Coffee Cup - 250ml, re-usable, recyclable, suitable for hot liquids and dishwasher-safe.

**Comment by siuhoylee** [comment]
@marcwalsh   @sabrinang   https://redpen.io/p/sqd7119783252f21b2  Here is a mockup of the coffee cup colours and the MozFest logo. I think the cups look nicer with whiteout cog minus the black square. Let me know your thoughts. 
<img width="356" alt="2018 water bottle" src="https://user-images.githubusercontent.com/53485444/64179238-ba54aa00-ce5a-11e9-8d7d-9c02d06cbcfb.png">
<img width="600" alt="MozFest pen case" src="https://user-images.githubusercontent.com/53485444/64179285-c93b5c80-ce5a-11e9-9fb9-d7c5055014c0.png">

**Comment by siuhoylee** [comment]
@sabrina  @marc  We had a meeting with Sarah Allen and discussed placing the 10th Anniversary graphic onto the coffee cups. In Red Pen there is V2. I think it is a good idea and looks good. Please add any comments. Thanks.

**Comment by siuhoylee** [comment]
@sabrina  @marc  There is V3 in Red Pen with 3 further designs with my notes. Please add any comments. Thanks.

**Comment by siuhoylee** [comment]
Final print ready artwork can be found here  https://drive.google.com/drive/folders/12gdPaw2IH4YZl-m4Spu9qPd-uNGuOoWF
![Mozilla Festival-coffee cup](https://user-images.githubusercontent.com/53485444/64690844-45502880-d489-11e9-8721-54a1a77cf2c9.jpg)

**Comment by sabrinang** [comment]
@siuhoylee For the position of the artwork, I think the bottom margin is still a bit close to the edge and can match the top (especially if it shifts in printing). Can you adjust the file? See ref below:

<img width="246" alt="image" src="https://user-images.githubusercontent.com/2492510/64739940-86a40080-d4a8-11e9-855e-f067459d5163.png">

**Comment by sabrinang** [comment]
@siuhoylee Thanks for clarifying that the mockup above up is inaccurate and forwarding over the print proof of how the artwork is placed in print production (I've also included it in the folder for reference but please include anything else I may of missed)
<img width="665" alt="image" src="https://user-images.githubusercontent.com/2492510/64820659-b2d18700-d565-11e9-84aa-818c9c7ad38a.png">

R+ on design and print margins on proof. Ready for print.

**Comment by siuhoylee** [comment]
Margins were adjusted in the printers proof.

**Comment by marcwalsh** [comment]
Sent to print! 🎉

**Comment by sabrinang** [comment]
**Post-MozFest Documentation**
Available in four colours by coffee stations
![DSC04049](https://user-images.githubusercontent.com/2492510/68496974-59ee3a00-0208-11ea-9658-8b4f825f9f6f.jpg)
![DSC04054](https://user-images.githubusercontent.com/2492510/68496980-5b1f6700-0208-11ea-8fba-b0ca25980769.jpg)
