### ISSUE TITLE
Where should we feature the live D&D stream?

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/mozfest-design-2019#44]
This is purely a feedback/discussion ticket -- no design or engineering deliverables should come out of this.

The MozFest team is wondering where would be the best place to embed the live Dialogues & Debates youtube stream on the website? Should it be on the homepage, if so, where do you think would fit best (content can be reduced if needed). Should it be on the D&D page maybe? The goal is to have a low bounce-rate on this.

Think of it from an engagement perspective as well -- a lot of people will watch the D&D series live. Can we get them to signup? Should we have a button to take them to our newsletter page to signup to our list?

@marcwalsh you had some data analyzed from the way we showed last year's live stream, can you share that with us?

Assigning to myself to drive this.

cc @kristinashu, @anilkanji, and @sabrinang

**Comment by anilkanji** [comment]
Considerations/questions:
- when you say website, do you mean the mozfest site? if so home page of that makes sense to me.
- from an engagement perspective, I was watching the youtube live streams last year, and I saw numbers in the 100s watching. Was that wrong? Or to put it in another way - show me data that says tons of people watched :)
- is there a way folks can feedback or ask questions to speakers via our site? that could be a reason for signing up and providing an email address. it's also a huge lift if it hasn't been prebuilt
- instead, is there a content upgrade we can offer? something like - "enjoying this live stream? sign up to get the full mozfest wrap videos and insider q&a
- conversion from video content goes way up when there is a specific call to action in the video itself - ideally through text and words (audio). would we be able to coordinate this? it's a consideration...

**Comment by gideonthomas** [comment]
Awesome feedback, thanks @anilkanji! Here are some thoughts/comments:

> when you say website, do you mean the mozfest site? if so home page of that makes sense to me.

Yep the MozFest site.

> from an engagement perspective, I was watching the youtube live streams last year, and I saw numbers in the 100s watching. Was that wrong? Or to put it in another way - show me data that says tons of people watched

Good call. @marcwalsh can you provide this data please?

> is there a way folks can feedback or ask questions to speakers via our site? that could be a reason for signing up and providing an email address. it's also a huge lift if it hasn't been prebuilt

That's a neat idea. @marcwalsh what do you think about this from a programming perspective? Is it feasible to coordinate something like this?

> is there a content upgrade we can offer? something like - "enjoying this live stream? sign up to get the full mozfest wrap videos and insider q&a"

Hmm, since the nature of this is sales-like, I don't think we have enough information about the people who watch this to tailor an effective pitch to them. @marcwalsh do we have any insight on personas for the people who watch the stream?

> conversion from video content goes way up when there is a specific call to action in the video itself - ideally through text and words (audio). would we be able to coordinate this?

I think we can. e.g. vote for the most creepy product in the Buyer's Guide. @marcwalsh can you check with Sarah about whether we can do something like this maybe between talks or something?

**Comment by gideonthomas** [comment]
@marcwalsh just throwing this back on your radar to look at and provide feedback and data.

**Comment by marcwalsh** [comment]
Data from GA in from October showed we had 8.5K users visit the site (13K sessions) who clicked on the snippet advertising the D&D live stream - this only lead to a a couple of hundred people watching the stream live.

I'll loop in @KevZawacki around Live Q&A, I'm not sure how we can capture it, or if there's a way of live polling. I think last year we had something that allowed it for one of the sessions but I think it would be a great way of increasing engagement on the stream.

Afraid we don't have personas, the snippet was live on Release, Beta, Dev and Nightly last year so covered a wide range of people. 

We'd want to avoid having CTAs on camera, however there's the oppertunity to have ads between talks. Last year we had some generic Mozilla and FireFox videos, so there is space if you would want to add anything. They would just need to be delivered the week before the festival to make sure they make it into our rundown.

**Comment by KevZawacki** [comment]
Hi -- we've used a remote Q&A tool in the past, but it's proved more trouble than it's worth. It adds another level of complexity for the A/V team, and ends up distracting the speaker.

**Comment by gideonthomas** [comment]
Hmm, so a couple of hundred people doesn't seem like a compelling number to optimize engagement for. 

If we've tried the live Q&A activity and it hasn't worked due to logistics, I agree, let's not do it again this year since we all have a lot on our plates already.

I think this probably means that we can leave the video on the homepage as initially planned, but I don't think there's an engagement piece here.

@anilkanji what do you think?

**Comment by anilkanji** [comment]
Agreed @gideonthomas - maybe we can do something low bar for engagement like have a text CTA something like "Join the conversation at #2019mozfest" with a link to Twitter [using the actual hashtag].

**Comment by gideonthomas** [comment]
@marcwalsh just looping you in on this as an fyi about our path ahead ^
