### ISSUE TITLE
Wayfinding: Floor Entrance + Stair Stickers

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2019#45]
### Description:
This floor sticker system includes arrows, floor numbers, and space name stickers that will be stuck on the floor and stairs to direct attendees to specific areas. These will be reused from last year (we will keep Barlow typeface) and add new areas to the set

**This collection of existing stickers that could be reused/revised**
- [ ] MozFest (Gear) Logo
- [ ] MozFest Lockup
- [ ] Space/Experience Labels _(Web Literacy, Openness, Digital Inclusion, Decentralisation, Privacy & Security, Youth Zone)_
- [ ] Space/Experience Icons _(Web Literacy, Openness, Digital Inclusion, Decentralisation, Privacy & Security, Youth Zone)_
- [ ] Floor Numbers _(M, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9)_
- [ ] Arrows _(side, diagonal, large)_
- [ ] Debates and Discussions
- [ ] MozHelp
- [ ] Mozilla Zone
- [ ] Quiet Space
- [ ] Internet Research Hub
- [ ] Emergent Sesssions
- [ ] Lounge

**New stickers to add to the set**
- [ ] 10th Anniversary Motif
- [ ] Space/Experience Labels _(Queering, Neurodiversity, Arts & Culture)_
- [ ] Space/Experience Icons _(Queering, Neurodiversity, Arts & Culture)_
- [ ] Presenting Sponsors

**Format**
StickerMule print these as oversized stickers and print as large as 1.48m x 5m format.

**Quantities:**
TBD

### Reference from Last Year:
**Google Drive Files:** https://drive.google.com/open?id=1C9Dit63FYWGj1tpFy65Kd6RgwBAlV_BX&authuser=sabrina@mozillafoundation.org&usp=drive_fs
**Github Issue:** https://github.com/MozillaFoundation/mozfest-design-2018/issues/48

**Comment by marcwalsh** [comment]
Talking with @siuhoylee these are what's required for this year:
- [ ] Remove 'MozFest' from 'Queering MozFest' 2018 sticker
- [ ] Queering Icon
- [ ] Neurodiversity Icon
- [ ] Neurodiversity Space Name
- [ ] Change Art + Data to Arts and Culture
- [ ] Element AI logo sticker
- [ ] Coil logo sticker

**Comment by siuhoylee** [comment]
@sabrinang  @marcwalsh  Designs are on Red Pen https://redpen.io/p/zka960d01be5396af0

**Comment by sabrinang** [comment]
@siuhoylee Left some feedback on redpen 

Check if these additional labels are needed to be included: https://drive.google.com/open?id=1gW7Ij-0swG2WXRthhpeUbwX2bXDbHstb

**Comment by siuhoylee** [comment]
@sabrinang  @marcwalsh  Following on from our meeting, I have amended the Isometric Shapes Floor Stickers to have the words Healthy AI integrated in it. The sizes of each are around 690mm wide x 780mm h. I think the maximum size of floor sticker we can have is 1480mm x 5000mm. Its called V2 Isometric Shapes in Red Pen  https://redpen.io/p/zka960d01be5396af0

**Comment by marcwalsh** [comment]
Once these are ready, they need to be placed on an A1 or A0 canvas and will be printed as one big sheet at Ravensbourne.

**Comment by sabrinang** [comment]
After checking floor banners/maps, it seems like we are missing floor stickers?
- two for Arts & Culture? (specifically one for Gallery, one for Salon)
- Quiet Room
- MoZone
- Innovation Lounge
- Emergent Sessions 
- The Commons

**Comment by siuhoylee** [comment]
@sabrinang  @marcwalsh  The Floor Entrance and Stair Stickers artwork is in gdrive. The artwork is placed on 3 A0 width documents to be printed on-site at Ravensbourne. The isometric shape floor stickers will be white lines and text and transparent background. The link to the artwork: https://drive.google.com/drive/folders/1nK-JedxjBXWKleijZ0kidnDPx41qNdmK
<img width="911" alt="Screenshot 2019-10-23 at 09 58 36" src="https://user-images.githubusercontent.com/53485444/67377417-86098a00-f57d-11e9-838f-97fb5bce453a.png">
<img width="911" alt="Screenshot 2019-10-23 at 09 58 59" src="https://user-images.githubusercontent.com/53485444/67377435-8efa5b80-f57d-11e9-9a7e-055405adb7a4.png">
<img width="911" alt="Screenshot 2019-10-23 at 09 59 25" src="https://user-images.githubusercontent.com/53485444/67377444-915cb580-f57d-11e9-9f8f-728e1672e293.png">
<img width="908" alt="Screenshot 2019-10-23 at 10 00 08" src="https://user-images.githubusercontent.com/53485444/67377452-9588d300-f57d-11e9-983f-cc85fcb70afb.png">

**Comment by sabrinang** [comment]
**Post-MozFest Documentation** 
Adjusted shape floor stickers to be black lines on transparency for windows instead:
![48998571697_5e5d86e1b3_6k](https://user-images.githubusercontent.com/2492510/68440775-ef45eb80-0180-11ea-82a3-e089c6a3acc4.jpg)

Sponsorship stickers placed by first stairwell
![48997824063_843b0f1966_k](https://user-images.githubusercontent.com/2492510/68440825-13093180-0181-11ea-8b29-cfb20b9fbfbb.jpg)

10th anniversary motifs in walkway and entrance
![IMG_20191025_174650](https://user-images.githubusercontent.com/2492510/68440857-2caa7900-0181-11ea-8f81-1b00a7f2e9ce.jpg)
![IMG_20191025_174709](https://user-images.githubusercontent.com/2492510/68440858-2d430f80-0181-11ea-86e1-f0a2ad267cd9.jpg)
![DSC04211](https://user-images.githubusercontent.com/2492510/68440912-506dbf00-0181-11ea-9275-d6ea12f23360.jpg)

Stair sticker wayfinding 
![DSC04108](https://user-images.githubusercontent.com/2492510/68440939-64192580-0181-11ea-8f61-dc5c91932289.jpg)
![DSC04110](https://user-images.githubusercontent.com/2492510/68440944-68ddd980-0181-11ea-9cf5-6f7a3a5fc96c.jpg)
![DSC04186](https://user-images.githubusercontent.com/2492510/68440953-7004e780-0181-11ea-80c8-2b577b62c583.jpg)
![DSC04193](https://user-images.githubusercontent.com/2492510/68440957-72ffd800-0181-11ea-8a79-ffb117c700f3.jpg)
![DSC04213](https://user-images.githubusercontent.com/2492510/68440962-76935f00-0181-11ea-93c0-ef9a5ff238e5.jpg)

Youth Zone sponsorship and wayfinding
![IMG_20191025_174908](https://user-images.githubusercontent.com/2492510/68440993-8e6ae300-0181-11ea-84dc-11eb80d26478.jpg)
