### ISSUE TITLE
Wayfinding: Space, Entrance and Floor Banners

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2019#46]
### Description:
Large banners indicating the space or area along with the floor number are hung off the railing on each floor and at the entrance of each area so that they are visible throughout the venue. Unlike previous years, this will be printed on paper materials that can be recycled. If new spaces are added, they can be added later.

**Format**
Dimensions: Large (100cm x 200cm) & Small (75cm x 150cm)
If we are printing on paper you may need to change the bleeds as it was using a pixart template previously.

### Reference from Last Year:
**Google Drive Files:** https://drive.google.com/open?id=1DFNETrJDXkittwuQgOxA2ecxbMPjrJjF&authuser=sabrina@mozillafoundation.org&usp=drive_fs
**Github Issue:** https://github.com/MozillaFoundation/mozfest-design-2018/issues/41

**Comment by marcwalsh** [comment]
## Designs to be reused:

### Floor Number Banner
- [x] Level 0
- [x] Level 1
- [x] Level 2
- [x] Level 3
- [x] Level 4
- [x] Level 5

### Space Name Banner
- [x] Youth Zone
- [x] Web Literacy
- [x] Decentralisation
- [x] Digital Inclusion
- [x] Privacy and Security
- [x] Openness
- [x] Dialogues and Debates

## New Designs / Designs Requireing Updates for 2019:

### Floor Number Banner
- [x] Level M (New Colours)
- [x] Level 6 (New colours showing Decentralisation / Queering / **Digital Inclusion**)
- [x] Level 7 (Openness and Neurodiversity Colour - _Use 2018 Level 6 as template_)
- [x] Level 8 (Update to Privacy and Security and Arts and Culture Colour - _Use 2018 Level 6 as template_)
- [x] Level 9 (Generic Colour - Same as Level 1 from 2018)
 
### Space Name Banner
- [x] Innovation Lounge
- [x] Queering 
- [x] Neurodiversity
- [x] MoZone
- [x] Arts and Culture Saloon
- [x] Arts and Culture Gallery
- [x] The Commons
- [x] Quiet Room
- [x] Gaming

**Comment by siuhoylee** [comment]
@sabrinang  @marcwalsh   Here is the Red Pen link to the banners created so far  https://redpen.io/p/jc95c526f9dc404c0d  They are the same dimension and template as 2018. Here is link to the artwork on Gdrive as editable Illustrator files but not Final print ready pdfs.  Please advise if we have icon and colour for Arts and Culture/MoZone. Also please confirm final naming of Catering Area.

**Comment by siuhoylee** [comment]
Here is the link to the artwork on gdrive. https://drive.google.com/drive/folders/11rvUE3ExldUPmUVB92EV4SLBHiMlFFn7

**Comment by sabrinang** [comment]
I left a comment regarding Art and Culture/Experiences and Mozilla Zone in the festival guide issue here: https://github.com/MozillaFoundation/mozfest-design-2019/issues/35#issuecomment-534669819

If you are going with the same direction for banners, there is already a Mozilla Zone banner made from last year (so you don't need new icon/colour):
<img width="226" alt="image" src="https://user-images.githubusercontent.com/2492510/65550715-0da79e80-ded5-11e9-91c2-741b98877cee.png">

Also, left feedback re gradients on redpen.

**Comment by siuhoylee** [comment]
@sabrinang  @marcwalsh  The previous banners have been amended and the rest are on Red Pen  https://redpen.io/p/jc95c526f9dc404c0d for review

**Comment by sabrinang** [comment]
@siuhoylee Left some feedback on redpen 

Check if these additional labels are needed to be included: https://drive.google.com/open?id=1gW7Ij-0swG2WXRthhpeUbwX2bXDbHstb

**Comment by sabrinang** [comment]
@siuhoylee left some comments in the redpen. I think only mozilla festival wordmark + motif or healthy AI banners are missing.

**Comment by siuhoylee** [comment]
@sabrinang   @marcwalsh   Here is the link to the final artwork on gdrive https://drive.google.com/drive/folders/11rvUE3ExldUPmUVB92EV4SLBHiMlFFn7
![Space-Name-Banners](https://user-images.githubusercontent.com/53485444/65960325-215e8200-e44c-11e9-9ba0-e5ba006171fb.jpg)
![Floor-Number-Banners](https://user-images.githubusercontent.com/53485444/65960328-23c0dc00-e44c-11e9-8a35-3b41ded6cd5f.jpg)

**Comment by siuhoylee** [comment]
@sabrinang  @marcwalsh  Café space name banner has been renamed to The Commons. Artwork has been updated in gdrive.
![Floor Number and Space Name Banners](https://user-images.githubusercontent.com/53485444/65972597-fbdc7300-e461-11e9-8006-6725ca02f519.jpg)

**Comment by sabrinang** [comment]
@siuhoylee left some comments on redpen https://redpen.io/meca1979469a806497 and referring to Marc's previous comment https://github.com/MozillaFoundation/mozfest-design-2019/issues/46#issuecomment-534104787 :

- I don't think Art+Data will be reused for 2019?
- is M floor needed? (not on list)
- Quiet Space (last year) or Quiet Area (as typed on list)?
- Is it Art & Culture suppose to be "Arts and Culture Saloon"? or are these two separate things?
- Does "Catering Area" need to be included?
- assuming "emergent sessions" is kept from last year and "the commons" is new addition not on list

@marcwalsh Can you confirm & clairfy these content pieces?

I'll review design after content is final

**Comment by Saallen** [comment]
I can jump in here

* Art + data is not being used for 2018
* M is the Mezz level on level 1 
Arts and Culture space is divided into two- Salon on level 8 and Gallery in Mezz - 
Mezz level Mezz Arts and Culture Gallery
Level 8 is Arts and Culture Salon ( as in the french word not the wild west version 🤠 )
Please ensure to write Arts not just art


* Quiet space is actually now just a room. Maybe best to call it that?

* The commons is where lunch is served over the three days- using this word instead of Catering as it sounds nicer

*Emergent sessions is still taking place and in the commons area

@marcwalsh in case I got anything wrong

**Comment by marcwalsh** [comment]
Thanks @Saallen 

@siuhoylee:

- Update the Art + Culture to Arts + Culture, you can use this design on both M and 8 (just add 'Gallery' to one and 'Salon' to the other).
- Update the Level M colour to match the Arts and Culture space
- Update Quiet Space to Quiet Room

If you can make those changes for now and export them, I can then get the copies that are already confirmed printed. Once I get the name of the Sponsor Space I'll update, but lets not let us block design / review as we can get the other sent to the printer.

**Comment by siuhoylee** [comment]
@sabrinang  @marcwalsh  The updated banners V3 are on Red Pen  https://redpen.io/p/jc95c526f9dc404c0d Updated Space Name Banners are Arts & Culture Gallery, Quiet Room, Innovation Lounge, Gaming MozFest, Arts & Culture Salon. (The Gaming MozFest banner has been updated to match with the updated icon in the maps ie no shading in the cubes and blue outline instead of white. The Floor M number banner has been updated too. The gdrive link to Floor Number Banners https://drive.google.com/drive/folders/1K_wz-fFtaGEJVcPMolSaM7saXcAWqhkZ    The gdrive link to the Space Name Banners https://drive.google.com/drive/folders/1AnK89lxDdYPcVQ_9CkKDsdKEA3-XNDhq
![Updated Space Name and Floor Number Banners Overview](https://user-images.githubusercontent.com/53485444/66571271-e0aaeb00-eb66-11e9-9456-cb7608ca6f68.jpg)

**Comment by sabrinang** [comment]
@siuhoylee The design itself look good. I'm not sure what printer templates these are on as the artboards are 180cm (previous artboards were 158.8 cm) but thanks for exporting the 5mm bleeds.

Can you place all the files in the final print folders so they can be found in one place?
Missing number pdf: 0, 1, 2, 4, 5
Missing spaces pdf: dialogues and debates, youth zone, web literacy, gaming mofest, digital inclusion, decentralization, open innovation, privacy & security, emergent sessions

**Comment by marcwalsh** [comment]
Sent to print!

M

**Comment by sabrinang** [comment]
**Post-MozFest Documentation**

![DSC04045](https://user-images.githubusercontent.com/2492510/68497143-bf422b00-0208-11ea-8b4b-3193b5f2f502.jpg)
![IMG_20191026_131644](https://user-images.githubusercontent.com/2492510/68497261-fdd7e580-0208-11ea-8760-aa4c2b187050.jpg)
![IMG_20191025_173110](https://user-images.githubusercontent.com/2492510/68497252-f87a9b00-0208-11ea-9676-cb1fd9054371.jpg)

This should of been aligned top-down according to set up guide. I believe people who were setting up were blocked by banners/furniture during their set-up
![DSC04276](https://user-images.githubusercontent.com/2492510/68497243-f0baf680-0208-11ea-9fc0-e85b4ac7b4e1.jpg)

![DSC04072](https://user-images.githubusercontent.com/2492510/68497167-cb2ded00-0208-11ea-9946-9cd977ecd698.jpg)
![DSC04168](https://user-images.githubusercontent.com/2492510/68497206-dc76f980-0208-11ea-97ad-ac7547852b6b.jpg)
