### ISSUE TITLE
Volunteer T-Shirts

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2019#47]
### Description:
Branded t-shirts for MozFest House and the Festival will be worn by volunteers. The T-Shirts will also contain logos of the Presenting Sponsor(s). The back will have the #MozFest and it has been preferred to have the date present as it is seen as a collectable by volunteers.

### Format
- Mozilla Festival: Front and Back of T-shirt A4 size (printable area)
- Mozilla Festival House: Front of T-Shirt only and A4 size (printable area)
- Sponsorship
- Make sure we can get the quantity in the colour we want early to ensure we have the amount we need.

### Reference from Last Year: 
Google Drive Files: https://drive.google.com/open?id=1qfFeiPguba0IldUcrlw5_6fgr1ek7WsE&authuser=sabrina@mozillafoundation.org&usp=drive_fs
Github Issue: https://github.com/MozillaFoundation/mozfest-design-2018/issues/61

**Comment by siuhoylee** [comment]
@marcwalsh   @sabrinang  Here is the Red Pen link to the 2019 Volunteer T-Shirts. https://redpen.io/p/ysedf0c644c00e3b5f

**Comment by marcwalsh** [comment]
+1 to @sabrinang's comments on redpen to using the raditated design, but with the pattern decreasing in size as the screenprinting would only be in white. 

The back design works, just requires changing logos. The sponsor logos to inlcude are:
- ElementAI
- Coil

**Comment by siuhoylee** [comment]
@sabrinang  @marcwalsh  V2 of the amended Volunteer T-Shirts are on Red Pen. I have placed on to the artwork, the received Coil logo from Jesse.  https://redpen.io/p/ysedf0c644c00e3b5f

**Comment by sabrinang** [comment]
@siuhoylee left comments on redpen.

**Comment by siuhoylee** [comment]
@sabrinang  @marcwalsh  Sabrina, I have made the amends. Please let me know of feedback. Thanks. V3 is on Red Pen https://redpen.io/p/ysedf0c644c00e3b5f

**Comment by sabrinang** [comment]
@siuhoylee I left feedback for refining radiating square effect on redpen, the back of the shirts look good. Here are some tips that could help which could also apply to https://redpen.io/cw1c2b2c00ee1ca610 the poster as I mentioned it there as well if you are using the effect again there: 
<img width="1465" alt="Screen Shot 2019-10-01 at 1 36 45 PM" src="https://user-images.githubusercontent.com/2492510/65999032-6e912280-e451-11e9-9446-299a700da3f3.png">

(if you need these notes in .ai I left them [here](https://drive.google.com/open?id=155CwOhZsldgnZgm7L-b4SVTou1nG5246&authuser=sabrina@mozillafoundation.org&usp=drive_fs) )

**Comment by siuhoylee** [comment]
@sabrinang  @marcwalsh   V4 is in Red Pen  The radiating pattern should be all uniform now and I have 'tidied up' the corner squares too.

**Comment by siuhoylee** [comment]
@sabrinang  @marcwalsh  Presenting Festival Partners on the back has been updated to Presenting Festival Sponsors. V5 https://redpen.io/cwda675c3a25a8713d  
![MozFest Volunteer T-Shirt](https://user-images.githubusercontent.com/53485444/66063953-5ba74c80-e53c-11e9-8f91-a0f3ee13cb77.jpg)

**Comment by sabrinang** [comment]
Does MozFest House also needs to say "sponsors" instead of "partners"? Otherwise, I have no more design feedback on redpen so you can export to gdrive and tag me to design review print files :)

**Comment by siuhoylee** [comment]
@sabrinang  @marcwalsh  The MozHouse Volunteer T-Shirt has been updated on the back to say 'Presenting Festival Sponsors'. V4 is in Red Pen. The artwork is in gdrive. I have saved the MozFest House T-Shirt into the MozFest House Folder (thinking that all MozFest House assets should be together in one folder) https://drive.google.com/drive/folders/1Bpc25lZejSkFbCGK1Rv7-cd_KBDG1lx2     The MozFest T-Shirt is saved into the Mozilla Festival 2019/Volunteer T-Shirt folder https://drive.google.com/drive/folders/15MAntt6aHwoVBWleC_rUbVBsA615KRC-
![MozFest-House_Volunteer-T-Shirt](https://user-images.githubusercontent.com/53485444/66114841-8db1c080-e5c7-11e9-8f81-c035c8535b80.jpg)

**Comment by sabrinang** [comment]
@siuhoylee The designs look good but just pointing out last year they were exported on A4 or A3 for print so I may need those print exports for review.

@marcwalsh Can you let us know what the printer requires? If there's a prefered printable areas size, template or if a mockup is enough for them to print the designs from?

**Comment by marcwalsh** [comment]
Thanks @siuhoylee and @sabrinang - they were able to work through the files that Siu uploaded. 

Sent to print - due for delivery on the 17th October

I was also able to order both unisex and women's cuts this year

👕

**Comment by sabrinang** [comment]
**Post-MozFest Documentation**
![48998503797_2fbfc059cd_k](https://user-images.githubusercontent.com/2492510/68497559-ac7c2600-0209-11ea-8b21-9467116d44d9.jpg)
![48998343196_43c3f4fd05_k](https://user-images.githubusercontent.com/2492510/68497732-1a285200-020a-11ea-8c01-f283e25962d8.jpg)
