### ISSUE TITLE
Science Fair demo poster template

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/mozfest-design-2019#49]
### Context

The science fair 10th anni room will showcase people, projects and collaborations of the last ten years. The aim is to highlight the movement, the many disciplines, organisations and breadth of work that is connected through MozFest. Each  demo table will host a project or organisation that came to MozFest many years ago, and highlight the work they are doing today- Mark Surman requests that we create a poster with a frame for demos to fill in. The first section shares when this project/organisation came to MozFest and second section shares what they are demo-ing on the day

### Ask

A poster template that can be filled in by demo facilitators at the science Fair. The poster will contain prompts which can be filled in. Let's create three templates (all of them have the same design, just one small copy tweak between them -- us vs. me vs. missing one prompt)

### Copy

---
About My Story [Logo space]

"My story at MozFest started in ... as ..."
"Today, I present ..."

---
About Our Story [Logo space]

"Our story at MozFest started in ... as ..."
"Today, we present ..."

---
About Us [Logo space]

"Today, we present ..."

---

**Comment by sabrinang** [comment]
@gideonthomas Are there any preference or recommendations on dimensions for this?

**Comment by gideonthomas** [comment]
@sabrinang per Sarah - "Emmm, I am thinking A4??"

**Comment by sabrinang** [comment]
The three poster template designs are on redpen: https://redpen.io/p/xj5a344ef7c09a929b

For the section for the “My/Our Story at MozFest…” section, did they want this as one section and the sentence as is or in separate boxes like I have in redpen? If there are any preferences, feel free to leave feedback.

The poster is design at A4 and I'm wondering will this be printed at Pixart? If so I can use a template from pixart, if not I can export a 1/8” bleed.

**Comment by marcwalsh** [comment]
@sabrinang - ideally yes - attached is the template, I'm going to print on either recycled or wooden fibre paper.

[pixartprinting-template-small-format-flyers-and-leaflets.pdf](https://github.com/MozillaFoundation/mozfest-design-2019/files/3707986/pixartprinting-template-small-format-flyers-and-leaflets.pdf)

**Comment by sabrinang** [comment]
I've exported the print pdf on the pixart template on google drive here: https://drive.google.com/open?id=18t2oQJGiEpIkA7bPZaIxqZoaSTZli4Ey&authuser=sabrina@mozillafoundation.org&usp=drive_fs

@Saallen can you review that this content format is what you'd like for these posters? you can also leave any specfic feedback on the [redpen](https://redpen.io/p/xj5a344ef7c09a929b)

**Comment by Saallen** [comment]
Hey @sabrinang  
Looks great- my only comment - how do we make it clearer which section they write their name and which section they share info about the demo? Right now thats a little unclear

**Comment by sabrinang** [comment]
@Saallen 
I updated two templates on [redpen](https://redpen.io/p/xj5a344ef7c09a929b) with additional copy to include `Name` section and `Demo Info` title to make separate sections more distinct; third template unchanged. 

Please review if this is more clear.

**Comment by Saallen** [comment]
Hey @sabrinang Sabrina- thank you- these look great- the prompts are perfect
Thanks 💮

**Comment by sabrinang** [comment]
Thanks Sarah!

Print pdf on gdrive here: https://drive.google.com/open?id=18t2oQJGiEpIkA7bPZaIxqZoaSTZli4Ey&authuser=sabrina@mozillafoundation.org&usp=drive_fs

Ready for print.

**Comment by sabrinang** [comment]
**Post-MozFest Documentation**

Seen near demos
![Image from iOS(2)](https://user-images.githubusercontent.com/2492510/68438991-e18d6780-017a-11ea-986a-00a4a12d3825.jpg)
