### ISSUE TITLE
Tablecloths

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/mozfest-design-2019#5]
### Description

We use tablecloths for registration, MozFest House, etc. ~This year, let's design a general purpose tablecloth that just has the Mozilla wordmark on it so that it can be rescaled, resized, and reused for other Mozilla events.~

Reuse same pattern or switch to black background with white logo. use different supplier.

### Reference from last year

**GitHub ticket:** https://github.com/MozillaFoundation/mozfest-design-2018/issues/43

**Comment by siuhoylee** [comment]
@gideonthomas  Hi Gideon, its Siu
I'm the MozFest designer in the London office.

**Comment by gideonthomas** [comment]
Hi @siuhoylee I've invited you to make changes in this github repo

**Comment by beccaklam** [comment]
@marcwalsh Did you save the tablecloths from last year so we can reuse them?
cc: @sabrinang @gideonthomas

**Comment by marcwalsh** [comment]
@beccaklam - I'll double check and see, we definietly have some but unsure if it's the MozFest tablecloths with the texture (https://github.com/MozillaFoundation/mozfest-design-2018/issues/43) or the MozFest House lockup version (https://github.com/MozillaFoundation/mozfest-design-2018/issues/67).

**Comment by kristinashu** [comment]
If we don't have the last year's table cloth then here is an updated PDF we could use (black background with white mozfest logo).

[Drive Folder ](https://drive.google.com/drive/folders/1l99UNFWhL3JdtiL_5TIM9LXldK02LtE4?usp=sharing)

[Mozilla-Festival-2019_Table-Cloth.pdf](https://github.com/MozillaFoundation/mozfest-design-2019/files/3585780/Mozilla-Festival-2019_Table-Cloth.pdf)

**Comment by marcwalsh** [comment]
We've received the items from storage and we have the tablecloths from last year, so do not need to print these.

Thanks!

**Comment by sabrinang** [comment]
**Post-MozFest Documentation**

Both the Weekend and House had rounded/new reception areas that didn't need table cloths. Info tables for spaces didn't use them either.
