### ISSUE TITLE
MF House wayfinding

### ISSUE THREAD

**Issue by LucieClick-MFHouse** [MozillaFoundation/mozfest-design-2019#50]
Hi @siuhoylee &  sabrina 
We have long tall units like the attached example (the Thoughtworks one) for wayfinding as they are thin so don't take up too much space.

Here is a proof as a base for wayfinding for all the rooms - some will have one name on and some multiple (hence why we can't out the room names vertically which I would have preferred.)

Also there is a hanging banner with same info - all attached below - can you let me know if you are happy with the concept?

![Qj4KmvdgTd6ZA%sVYEVQJg](https://user-images.githubusercontent.com/55188573/66159002-0132ec80-e61f-11e9-8b65-b0f70c460e72.jpg)
<img width="90" alt="Screenshot 2019-10-03 at 20 39 37" src="https://user-images.githubusercontent.com/55188573/66159031-0859fa80-e61f-11e9-8ab4-257e90627e82.png">
Hanging banner 
<img width="398" alt="Screenshot 2019-10-03 at 20 50 52" src="https://user-images.githubusercontent.com/55188573/66159282-9504b880-e61f-11e9-8400-c988ff826757.png">

**Comment by LucieClick-MFHouse** [comment]
@sabrinang

**Comment by sabrinang** [comment]
@LucieClick-MFHouse Yup concepts match the window so it's good, some feedback below:

**Narrow Standing Banner** 
- remove the logo in the centre that is cropped on the right side _(avoid cropped logos)_ . The lockup is right below anyway so it's redundant
- if each of these locations require a detachable black arrow in different directions leave enough room in between so it has room below _(assuming arrows would be positioned similarly to the hanging banner below)_
- I also prefer that this isn't set in all caps so it is similar to look like and match the hanging banner type that is more legible from a distance

**Hanging banner:** 
- on the lower right you can remove/relocate the isometric line shape behind the logo to simplify that area

**Comment by LucieClick-MFHouse** [comment]
<img width="529" alt="Screenshot 2019-10-04 at 11 01 19" src="https://user-images.githubusercontent.com/55188573/66209780-0ab86500-e6b0-11e9-9cdc-9d048b4ceb39.png">
<img width="396" alt="Screenshot 2019-10-04 at 14 05 44" src="https://user-images.githubusercontent.com/55188573/66209790-1572fa00-e6b0-11e9-9ebc-59cc96ef5836.png">
<img width="380" alt="Screenshot 2019-10-04 at 11 01 39" src="https://user-images.githubusercontent.com/55188573/66209800-199f1780-e6b0-11e9-9d67-8dcfcfc55c0e.png">

Hi - thanks @sabrinang ! See revised options. I have also added a graphic to do on the front of the reception desk which we are having in the foyer of the RSA - let me know if you are OK with these and I'll send to print.

**Comment by sabrinang** [comment]
Thanks for the revisions @LucieClick-MFHouse, R+ you can send them to print

**Comment by sabrinang** [comment]
**Post-MozFest Documentation**
@LucieClick-MFHouse If you had any photos of the wayfinding can you share here please? Thanks
