### ISSUE TITLE
Name Cards

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/mozfest-design-2019#51]
Name card ID for house and weekend

Needs
- content
- Designs required
- House card
- all weekend card
- saturday only card
- sunday only card
- science fair card

**Comment by marcwalsh** [comment]
We will have a name card allowing access to the event venue based on: https://github.com/MozillaFoundation/mozfest-design-2018/issues/62

Colours from 2018 which can be reused this year:

- House: Orange / Pink
- Friday Only: Green
- Saturday Only: Purple
- Sunday Only: Cyan
- Weekend: Blue

@zee-moz - I've placed 2018 content in this doc, let us know if anything needs rewording, however ideally @siuhoylee will reuse the rear design from 2018, with just updating the front cover. 

**Content Doc:**
https://docs.google.com/document/d/1PPfJ-YNMn-oZJ-sXkobskARdl3SFvV7WaeC1n-tpyBs/edit?usp=sharing

**Comment by siuhoylee** [comment]
@sabrinang  @marcwalsh  @Saallen  @zee-moz  The updated designs are on Red Pen  https://redpen.io/p/uj28c89aa9621be388  The back as discussed will look the same as 2018 but will have updated content. Awaiting content.

**Comment by zee-moz** [comment]
@marcwalsh @siuhoylee  I've suggested a few small changes for clarity to the content. Have a look!

**Comment by sabrinang** [comment]
@siuhoylee left some design feedback for name card fronts on redpen

**Comment by siuhoylee** [comment]
@sabrinang  @marcwalsh  V2 of amends are on Red Pen https://redpen.io/p/uj28c89aa9621be388  Updated back with supplied content from Zannah. I changed the word 'Level' to 'Floors', since that is how it is named in the maps. Also I changed the colour of the back of the Sunday Name Card so the colours match with the front. Link to artwork on gdrive is https://drive.google.com/drive/folders/1yU2Jn5yMf8BPh38xTcZovxkq4eP0qKrH
![V2 Name Cards Overview 2](https://user-images.githubusercontent.com/53485444/66588221-e662f980-eb83-11e9-9197-8c9877383b9e.jpg)

**Comment by sabrinang** [comment]
@siuhoylee Thanks for revising and size/bleeds are good. You can remove the holes from final design as we did not need them exported.

Content corrections need to be updated for Network/Password. From the content doc, the science fair card uses the same back content as MozFest House so you can reuse that design but make it green.

**Comment by siuhoylee** [comment]
@marcwalsh  @sabrinang  Updated V3 Name Cards is in Red Pen. The Science Fair back has been updated with the House content. The wifi password and network has been updated on Sat, Sun, Weekend. The punch holes have been removed on the final artwork as noted, Sabrina. I have exported the final pdf artworks in gdrive https://drive.google.com/drive/folders/1Yx5Jz6yHLff4ss3yR1jgmuPURSclqWAW  
![V3_Name Cards](https://user-images.githubusercontent.com/53485444/66652725-51690a80-ec2e-11e9-9e22-2f7417784049.jpg)

**Comment by sabrinang** [comment]
@siuhoylee Thanks for the updates and including hole reference for the printer separately. Looks good!

R+ Ready for Print

**Comment by marcwalsh** [comment]
Sent to print 🎫

**Comment by sabrinang** [comment]
**Post-MozFest Documentation**
![10222019-mozfest-house-tuesday-4](https://user-images.githubusercontent.com/2492510/68497868-61164780-020a-11ea-85af-95fde473d7a6.jpg)
![48997763463_74394f6199_k](https://user-images.githubusercontent.com/2492510/68497971-a20e5c00-020a-11ea-94db-f10bbc8f0e84.jpg)
![48997776933_b7ffd58f22_k](https://user-images.githubusercontent.com/2492510/68498017-c1a58480-020a-11ea-8b83-b4b46b1130e3.jpg)
