### ISSUE TITLE
Quiet room - poster

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/mozfest-design-2019#52]
Neuro team will share content they want for a poster that goes on the door to the quite room at MozFest
* The quiet room is on the first floor, at the back of the Mozone
* This poster will be printed onsite
* Lucie will confirm the content here

**Comment by patjouk** [comment]
Is it okay if I get back to you beginning of next week?

**Comment by marcwalsh** [comment]
Thanks @Saallen and @patjouk - we'll get this printed onsite at Ravensbourne, so have a bit of time.

**Comment by patjouk** [comment]
perfect, thank you!

**Comment by sabrinang** [comment]
@patjouk Hey Lucie, do you have any more information on the content you want for this piece?

**Comment by patjouk** [comment]
Yeah, sorry!
I have a draft here: https://docs.google.com/document/d/1pX82P1FEdaI5_3LfECWvFeQOQ5tiPDCpUWjoMvTzHus/edit?usp=sharing

I will check with Sarah this afternoon to finish it.

**Comment by taisdesouzalessa** [comment]
Hey @patjouk - I am working on this poster and I need your help on the last paragraph: 
"If you have any issues and need help, you can reach us on Slack in the neurodiversity chanel or find us on the 7th floor in the neurodiversity space. You can also ask a volunteer, they will be wearing X t-shirt"

1. Do we have the official slack channel name so I can include on it?
2. What's the shirt color? Currently we have "X t-shirt" in the copy. **EDIT: just saw on the top of the doc "Volunteers with blue tshirt". Should I be using that?**

Thanks!!

**Comment by taisdesouzalessa** [comment]
Here is the RedPen link: https://redpen.io/p/zd8080618c357a7a66

@sabrinang can you please take a look and let me know if there is any feedback?
Only missing thing is the channel on slack for the A1 poster.

**Comment by taisdesouzalessa** [comment]
Talked to @patjouk and we will be using the big A1 poster - print 2 copies.
The other one with "no laptop" won't be used since they have another one they made.

@sabrinang what's the next step to send this to print?

**Comment by taisdesouzalessa** [comment]
@siuhoylee here is the PDF to print: https://drive.google.com/file/d/1a2FTrd8QndnD781bQxxbpHnhzpAej7og/view?usp=sharing
We need: 2 copies
Size: A1
Let me know if you need help cutting this poster.

Can you let @patjouk and me know once this is printed?

**Comment by siuhoylee** [comment]
I just sent the Quiet Space Poster to be printed. I will let Lucie know
when it is done.

Regards
Siu

**Comment by patjouk** [comment]
Thanks again for your help for the quiet room poster. It was gorgeous!

**Comment by siuhoylee** [comment]
Print file is here: https://drive.google.com/drive/folders/1B0QD_UwASlhcSjzb4SS5X1tgAbhAZ_us  The poster got printed on Friday at Ravensbourne and whilst typos were corrected and sent to print before the print room closed for the weekend, it was too late to spot and amend the heading from Space to Room.
![Quiet-Room_Poster-A1](https://user-images.githubusercontent.com/53485444/67884104-2858dd00-fb3d-11e9-81db-ea0558be7b0e.jpg)
