### ISSUE TITLE
Static image for Science Fair screens

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/mozfest-design-2019#53]
Need image for screens around MozFest house. 
Can be static and will go on screens from 34'' to largest screen of 4 metres x 2.5 metres in great room - https://www.flickr.com/photos/mozfest/31778091128/in/album-72157699787459622/

Tag line for event is **10 years of activism, community, and collaboration**

Colours should match SF colours

**Comment by marcwalsh** [comment]
@siuhoylee  - this will need to be 1920x1080px as it's only on standard shaped displays / projectors

I'll assign you for now, with the milestone of the 25th since it's digital it can be delivered any time before the Friday of the Science Fair.

Thanks!

**Comment by sabrinang** [comment]
Redpen of Science Fair screen: https://redpen.io/p/zgfc02a883e8042a4b

Files on gdrive here: https://drive.google.com/open?id=1Bg21QeI19kv5y_CWklANKOpO8Y7Ba8Bd&authuser=sabrina@mozillafoundation.org&usp=drive_fs

@Saallen for review?

**Comment by marcwalsh** [comment]
Thanks @sabrinang - @Saallen approved this - closing!

**Comment by sabrinang** [comment]
**Post-MozFest Documentation**
Not certain if this was used
![Image from iOS(4)](https://user-images.githubusercontent.com/2492510/68498674-4b098680-020c-11ea-8389-a64a438e1205.jpg)
