### ISSUE TITLE
Screen: Motion Graphic video

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/mozfest-design-2019#55]
2018 ticket: https://github.com/MozillaFoundation/mozfest-design-2018/issues/36

Content to be provided by @marcwalsh

**Comment by natalieworth** [comment]
Hey @marcwalsh I'm just working on general screens right now (e.g. logo, etc.) Could you confirm that this information from last year is the same or if anything has changed:

    MozFest 2019 Logo
    Tagline
    Experiences (Queering MozFest, Gaming MozFest, Art + Data)
    Dialogue & Debates (times, talk, speaker, location)
    #mozhelp + info desk
    Social Media (hashtags, handles, platforms, pulse)
    WiFi (network, password)
    Schedule App
    Food (lunch, coffee)
    Internet Health Report
    Participation Guideline (email, phone)
    Sponsorship Slide (Presenting festival partner, Science Fair partner, Closing party partner and Youth Zone partner)
    Learn about Moz’s Fellowship and Awards programs on Level 1 (green slide)

**Comment by marcwalsh** [comment]
Hi @natalieworth - so sorry for the delay the majority of the content can stay the same as 2018 I've listed any slides that need updating below:


## New for this year

- [x] MozFest 2019 Logo
- [x] Tagline
- [x] Sponsors: Details are in the Festival Guide #35 (I'll add another note below with levels) // Sponsor logos can be found [here](https://drive.google.com/drive/folders/1QEpUzRBIGFa2BKKpRs_9Za97b2jAqeHB) 

## Update from last year

- [x] Dialogue & Debates (times, talk, speaker, location) can be seen in ~this doc~. (@KevZawacki linked a schedule below)
- [x] WiFi (MozillaFestival, MozillaFestival19)
- [x] Schedule App - Remove reference to App / Download and say 'View' instead - link is the same as last year
- [x] Food - Hot on Level 4 and Level 9, Grab and Go on Level 4, 6 and 9

## Same as 2018

- [x] #mozhelp + info desk
- [x] Social Media (hashtags, handles, platforms, pulse)
- [x] Coffee
- [x] Participation Guideline (email, phone)

**Comment by KevZawacki** [comment]
Hi @marcwalsh and @natalieworth 

That document is out of date -- here's the latest schedule: https://www.mozillafestival.org/en/speakers/2019/

**Comment by natalieworth** [comment]
@sabrinang @marcwalsh [Final File is here!](https://drive.google.com/open?id=1URwYe-oipdA5hkYUB1K_3H2ISFst147y)

**Comment by natalieworth** [comment]
> @sabrinang @marcwalsh [Final File is here!](https://drive.google.com/open?id=1URwYe-oipdA5hkYUB1K_3H2ISFst147y)

Updated the file and link/ fixed all the mistakes! Should be good to go :)

**Comment by natalieworth** [comment]
@sabrinang @marcwalsh The Level 4 stage screen ([looping) is here](https://drive.google.com/drive/folders/1UT15cU7ZBTEBgYxKnvYg245tHmWz3XrR?usp=sharing). Let me know if you need any changes.

**Comment by gideonthomas** [comment]
Hey @natalieworth just noticed that the pulse url is wrong -- should be mozillapulse.org not mozilla.pulse.org

**Comment by natalieworth** [comment]
@marcwalsh @gideonthomas Updated and uploaded the fixed [video here](https://drive.google.com/open?id=1G0W58zGPGAnLaOcrxIzPMBobA5jrlgMF)

**Comment by sabrinang** [comment]
**Post-MozFest Documentation**
![IMG_20191026_131733](https://user-images.githubusercontent.com/2492510/68498184-1943f000-020b-11ea-8abf-15c255218190.jpg)
![IMG-20191026-WA0001](https://user-images.githubusercontent.com/2492510/68498193-1f39d100-020b-11ea-90e5-c76d3e2936b1.jpg)
