### ISSUE TITLE
Poster: Dialogue & Debates

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2019#56]
Two posters to be placed outside Walker Space to display Dialogue & Debates speakers:
- Saturday
- Sunday

**Comment by sabrinang** [comment]
@KevZawacki @marcwalsh posters for review on redpen: https://redpen.io/p/rn03a53b786708d652

**Comment by KevZawacki** [comment]
Hi @sabrinang, these are wonderful :-) Thank you! I left two notes in RedPen, and have attached a relevant photo here.
![Chris Gray](https://user-images.githubusercontent.com/11045250/67298401-1d6dcf00-f4e3-11e9-9fb7-88da3bcf7453.jpg)


On a related note: Can we simply re-purpose these graphics for use on the screens in the Walker Space / elsewhere around the venue?

**Comment by KevZawacki** [comment]
@sabrinang Ah, I just saw the other GitHub ticket -- you can ignore my note about the screens!

**Comment by sabrinang** [comment]
Removed Desmond and added Chris. Redpen updated here: https://redpen.io/p/rn03a53b786708d652

Print PDFs with 0.125in bleeds exported here: https://drive.google.com/open?id=1EdMI1R5w3waO-vSZPOwF7ZahP_z_EMgp&authuser=sabrina@mozillafoundation.org&usp=drive_fs

**Comment by sabrinang** [comment]
**Post-MozFest Documentation**

Placed outside D&D space. Speaker got crossed out when cancelled and time blocks changed with masking tape. It might be good to not have times printed or to be digital only as they are prone to change so we have one source of reference that's up to date.
![DSC04045](https://user-images.githubusercontent.com/2492510/68436679-89069c00-0173-11ea-88cd-4a7e00a3faf6.jpg)
