### ISSUE TITLE
Screen: Dialogue & Debates

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2019#57]
Digital intro screens displayed near stage or for air.mozilla/youtube:
- Saturday
- Sunday

**Comment by sabrinang** [comment]
@KevZawacki for review: https://redpen.io/p/yw5ffb6e8cbf07a04b

JPG exports on gdrive here: https://drive.google.com/open?id=1DTxxX1kHnWfbmTcB6quPd4XyofK8VDca&authuser=sabrina@mozillafoundation.org&usp=drive_fs

**Comment by KevZawacki** [comment]
Thank you, @sabrinang!

**Comment by sabrinang** [comment]
Removed Desmond from schedule/photos and added Chris. Redpen updated and JPGs too.

**Comment by KevZawacki** [comment]
@sabrinang 🙏🙏🙏🙏

**Comment by sabrinang** [comment]
**Post-MozFest Documentation**

Used on video thumbnails and stream:
![Screen Shot 2019-11-07 at 4 53 45 PM](https://user-images.githubusercontent.com/2492510/68440300-6bd7ca80-017f-11ea-91f2-2babbc33d43b.png)
![48998299056_6071c78db5_k](https://user-images.githubusercontent.com/2492510/68440306-6f6b5180-017f-11ea-8101-57db59885bb4.jpg)
