### ISSUE TITLE
Large Sponsorship Banner

### ISSUE THREAD

**Issue by siuhoylee** [MozillaFoundation/mozfest-design-2019#58]
### Description:

Create a standing banner that feature all the sponsors located on the registration floor.

### Format:

Total graphic area: 750mm (w) x 2000mm (h)
Eco Banner stands are environmentally-friendly alternative to traditional roller banner stands that use plastic or metal components. They are made from 10mm thick ultra board, a 10mm thick cardboard with a honeycomb core made from 100% recycled material. The Eco banner is supplied flat packed in it's own cardboard box.

### Previous Application:

![Mozilla-Festival-2018_Large-Sponsorship-Banner](https://user-images.githubusercontent.com/53485444/67675850-209c0b80-f978-11e9-9d9d-154ba784e21a.jpg)

### Reference from Last Year
Google Drive Files: https://drive.google.com/drive/folders/1GJRcMoe1f0S7XeA3iIKOUYKhrKmQAknx
Github issue: https://github.com/MozillaFoundation/mozfest-design-2018/issues/49

**Comment by siuhoylee** [comment]
Here is the final artwork approved by Jesse and Marc.

<img width="317" alt="Screenshot-Large-Sponsor_Banner" src="https://user-images.githubusercontent.com/53485444/67677587-52af6c80-f97c-11e9-8641-ae860d88bfb0.png">

Print file is here: 
https://drive.google.com/drive/folders/1ns6apk67Z-MTDJqK3n9grw1_viJNTleO

**Comment by sabrinang** [comment]
**Post-MozFest Documentation**

Placed by entrance, floor 4 stage area & floor 5 Innovation Lounge
![IMG_20191026_131733](https://user-images.githubusercontent.com/2492510/68437804-e6e8b300-0176-11ea-8eb4-9fa50f739404.jpg)
![DSC04274](https://user-images.githubusercontent.com/2492510/68437884-34fdb680-0177-11ea-8494-29a649974306.jpg)
![48998365416_d70258be38_k](https://user-images.githubusercontent.com/2492510/68438291-86f30c00-0178-11ea-9119-d0931fd16270.jpg)
