### ISSUE TITLE
MozFest House Festival Guide

### ISSUE THREAD

**Issue by siuhoylee** [MozillaFoundation/mozfest-design-2019#59]
### Description:

A booklet guide that includes details about MozFest House events. The design will be relatively the same as 2018 with updated textures and colours.

### Format:

Custom size: 117mm (w) x 200mm (H). 4 pages including outer covers.

### Content:

https://drive.google.com/drive/folders/1dHzpMRDj866-yVO50qNyGXTxoMpKp5Hj

### Previous Applications:

![MozHouse Insert image 1](https://user-images.githubusercontent.com/53485444/67682517-7926d500-f987-11e9-88ff-c3459023f535.jpg)
![MozHouse Insert image 2](https://user-images.githubusercontent.com/53485444/67682526-7e841f80-f987-11e9-827d-5bbbd693254d.jpg)

### Reference from Last Year:

Google Drive Files: https://drive.google.com/drive/folders/1xbIRykPT-m-3GiOxLj8VY9Y0FiRPlbFe
Github issue: https://github.com/MozillaFoundation/mozfest-design-2018/issues/94

**Comment by siuhoylee** [comment]
Artwork is approved by Sarah Allen

Print file is here: https://drive.google.com/drive/folders/1Qd_TG81B0oJ4UG6wEritGY-hATBZlPwU

![Mozilla-Festival-2019_Festival-Booklet](https://user-images.githubusercontent.com/53485444/67684850-d3c23000-f98b-11e9-8a40-19cf50e46357.png)

**Comment by sabrinang** [comment]
**Post-MozFest Documentation**
Not sure if these got distributed (not seen at check-in?)
![Image from iOS(3)](https://user-images.githubusercontent.com/2492510/68498554-f7973880-020b-11ea-9ebd-f8a630d92b6c.jpg)
