### ISSUE TITLE
Opening ceremony live stream background

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/mozfest-design-2019#6]
### Description

The opening ceremony is streamed live on youtube. There generally is a slide background over which there will be the live stream as well as captions. Let's make a simple background with MozFest 2019 branding. This can also be a generic Mozilla branded background with the MozFest 2019 wordmark.

### Reference from last year

**GitHub ticket:** https://github.com/MozillaFoundation/mozfest-design-2018/issues/40

**Comment by gideonthomas** [comment]
Updating the textures is needed.

**Comment by gideonthomas** [comment]
We won't do names this year.

**Comment by sabrinang** [comment]
Iterations on plain and logo screens on redpen here: https://redpen.io/p/ak21c4a74658e0350b


PNGs exported in gdrive here: https://drive.google.com/open?id=1A43ZDlnzB-Nf4O9SXXFAVOe8tJWHiSmw&authuser=sabrina@mozillafoundation.org&usp=drive_fs

**Comment by sabrinang** [comment]
<img width="961" alt="Mozilla-Festival-2018_Screen-BG_5@2x" src="https://user-images.githubusercontent.com/2492510/66686906-c68c0e00-ec35-11e9-8993-ced40ab6adcf.png">
<img width="961" alt="Mozilla-Festival-2018_Screen-BG-Logo_5@2x" src="https://user-images.githubusercontent.com/2492510/66686907-c68c0e00-ec35-11e9-8fcb-8587f2d73826.png">

PNGs here: https://drive.google.com/open?id=1A43ZDlnzB-Nf4O9SXXFAVOe8tJWHiSmw&authuser=sabrina@mozillafoundation.org&usp=drive_fs

Ready for use.

**Comment by sabrinang** [comment]
@marcwalsh for review

**Comment by sabrinang** [comment]
**Post-MozFest Documentation**

I don't think these got used? I think slide templates were used https://github.com/MozillaFoundation/mozfest-design-2019/issues/3
