### ISSUE TITLE
Large Hackable Signs

### ISSUE THREAD

**Issue by siuhoylee** [MozillaFoundation/mozfest-design-2019#60]
### Description:

Design branded empty template signs for wranglers to make a sign for sessions hosted in their space.

### Format:

A1 portrait

### Previous Applications:

![large-hackable-sign_2018](https://user-images.githubusercontent.com/53485444/67693856-505c0b00-f99a-11e9-94a4-f1134b12c240.jpg)

### Reference from Last Year:

Google Drive Files: https://drive.google.com/drive/folders/1VWhFNSsxohKo6JPMN2rKQd_6s_SdGLZ1
Github Issue: https://github.com/MozillaFoundation/mozfest-design-2018/issues/50

**Comment by siuhoylee** [comment]
Print file is here: https://drive.google.com/drive/folders/1bKk0Tyy0rkybpxcBlFC31V1CU3nz8FYE

![A1-Hackable-Signs](https://user-images.githubusercontent.com/53485444/67697361-52c16380-f9a0-11e9-98e8-4c3baa3d1c11.jpg)

**Comment by sabrinang** [comment]
**Post-MozFest Documentation**

I seen that these were printed however I don't think they got used by wranglers. Perhaps they didn't pick them up or they were not distributed?
