### ISSUE TITLE
Sponsor Entrance Sign

### ISSUE THREAD

**Issue by siuhoylee** [MozillaFoundation/mozfest-design-2019#61]
### Description:

Youth Zone Entrance Signage with Sponsor Logo

### Format:

A0 size. Print on-site and mounted onto cardboard.

### Previous Applications:

These were printed A2.

![Mozilla-Festival-2019_Entrance-Signs](https://user-images.githubusercontent.com/53485444/67698147-b0a27b00-f9a1-11e9-8757-49c4bd1befbf.jpg)

**Comment by siuhoylee** [comment]
Print file is here: https://drive.google.com/drive/folders/10qLs6xk2rQS8IX1qnTfaEwUC4zMeMCPo

<img width="502" alt="Mozilla-Festival-2019_Youth-Entrance-Sponsor-Sign-A0" src="https://user-images.githubusercontent.com/53485444/67698823-f6ac0e80-f9a2-11e9-9065-6e28553c8f5a.png">

**Comment by sabrinang** [comment]
*Post-MozFest Documentation*

Mounted on cardboard and placed by Youth Zone entrance table.
![DSC04218](https://user-images.githubusercontent.com/2492510/68438841-60ce6b80-017a-11ea-8c42-9d805b81cc33.jpg)
![DSC04219](https://user-images.githubusercontent.com/2492510/68438842-61670200-017a-11ea-9c18-3dc837a567f4.jpg)
