### ISSUE TITLE
D&D Posters

### ISSUE THREAD

**Issue by siuhoylee** [MozillaFoundation/mozfest-design-2019#64]
### Desciption:

Schedule for dialogs and debates. The posters will be placed on the wall of the Walker Space.

### Format:

A2 printed on site

**Print file is here:** https://drive.google.com/drive/folders/1EdMI1R5w3waO-vSZPOwF7ZahP_z_EMgp

<img width="601" alt="Screenshot 2019-10-31 at 15 55 38" src="https://user-images.githubusercontent.com/53485444/67963751-0459d200-fbf7-11e9-92a4-95bcf7963d63.png">

<img width="601" alt="Screenshot 2019-10-31 at 15 56 26" src="https://user-images.githubusercontent.com/53485444/67963803-1f2c4680-fbf7-11e9-8e42-0aa4a6c8a774.png">

**Comment by sabrinang** [comment]
**Post-MozFest Documentation**

Placed outside D&D space. Speaker got crossed out when cancelled and time blocks changed with masking tape. It might be good to not have times printed or to be digital only as they are prone to change so we have one source of reference that's up to date.
![DSC04045](https://user-images.githubusercontent.com/2492510/68436679-89069c00-0173-11ea-88cd-4a7e00a3faf6.jpg)
