### ISSUE TITLE
Google Doc template

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/mozfest-design-2019#7]
### Description

Google Docs is used for localized comms cheatsheets and other purposes. Let's create (or reuse) a generic Mozilla branded google doc template for this.

### Reference from last year

**GitHub ticket:** Couldn't find - please edit this comment and link here if found

**Comment by sabrinang** [comment]
**Note to self to reference:**
Sponsorship Package: https://docs.google.com/document/d/1qHA73B_1idkAfldOk-wb3ftNfR3Xmg2TTuQhnHLkoOk/edit#heading=h.9dtxhg3nt1qp
MisInfo Package: https://docs.google.com/document/d/1eQNvNPFoAhOpUf9oCK8vCAqi0At_uXzFWml9vI-e2MQ/edit#heading=h.fs3gtczc7i18

**MozFest Use Cases:**
Comms Cheat Sheet: https://docs.google.com/document/d/1jTn78OyXn0SiMrz26CWXzeh-NbQQ7aiFAwV-GhuWFtA/edit?usp=sharing

- document generic template in brand home when complete

**Comment by sabrinang** [comment]
I made a template on gdoc here: https://docs.google.com/document/d/1VWB85eRkoOIdUTgiJ6iaTLkM_3ncX_jUggvJJuMnJbQ/edit?usp=sharing

I also documented this in brand home templates: https://foundation.mozilla.org/en/docs/brand/design/templates/
