### ISSUE TITLE
MozFest icon wall projection

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/mozfest-design-2019#8]
### Description

Determine if the icon can be reused for the wall projection or if we need to tweak it slightly.

### Reference from last year

**GitHub ticket:** https://github.com/MozillaFoundation/mozfest-design-2018/issues/34

**Comment by sabrinang** [comment]
Let's reuse it if we can and if we need the Mozilla Festival gear logo it is here (SVG): https://drive.google.com/file/d/1aqUhlBC02ERdi1ke2GrqjKo-QX6mcLop/view?usp=sharing

**Comment by sabrinang** [comment]
**Post-MozFest Documentation**

Located over main entrance
![DSC04208](https://user-images.githubusercontent.com/2492510/68495558-52796180-0205-11ea-8129-08a0af9e8340.jpg)
