### ISSUE TITLE
Mozilla festival wordmark/logo lockup

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/mozfest-design-2019#9]
### Description

Reuse what we had last year and just update to 2019.

### Reference from last year

**GitHub ticket:** https://github.com/MozillaFoundation/mozfest-design-2018/issues/8

**Comment by sabrinang** [comment]
I updated the annual lockup and files are exported here:
https://drive.google.com/open?id=1_OdkTPti3nZ5Y2VZ0CAQwJ8ueqVPk21f

This is also documented with our brand so it can be found: https://foundation.mozilla.org/en/docs/brand/design/logos/
